(()=>{
'use strict';
const FAST='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-patient-fast';
const CONDITIONS='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-conditions-v14';
const VISIT_API='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-visita-api';
const qs=new URL(location.href).searchParams;
const personId=qs.get('person')||'';
const key=localStorage.getItem('esf06_visit_key')||'';
const root=document.getElementById('root'),statusEl=document.getElementById('status');
let detail=null,condData=null,source='autorreferida';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=v=>String(v||'').toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase());
const fmt=v=>{if(!v)return'—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v)};
const age=v=>{if(!v)return null;const b=new Date(String(v).slice(0,10)+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a};
const active=c=>['ativa','latente'].includes(c.clinical_status||c.status);
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),3500)}
async function request(base,api,{params={},method='GET',body}={}){const u=new URL(base);u.searchParams.set('api',api);u.searchParams.set('k',key);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(u,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store',signal:ctl.signal});const j=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(j.error||`Erro ${r.status}`);return j}finally{clearTimeout(timer)}}
function flags(p){const f=p.flags||{},m=[['gestante','Gestante'],['hipertenso','Hipertensão'],['diabetico','Diabetes'],['acamado','Acamado'],['domiciliado','Domiciliado'],['oncologia','Câncer'],['pcd','Deficiência'],['saudeMental','Saúde mental'],['saude_mental','Saúde mental']];const out=[];m.forEach(([k,l])=>{if(f[k]&&!out.includes(l))out.push(l)});const a=age(p.birth_date);if(a!=null&&a<2)out.push('Criança < 2 anos');if(a!=null&&a>=60)out.push('Pessoa idosa');return [...new Set(out)]}
function render(){const p=detail.person,conditions=detail.conditions||[],visits=detail.visits||[];statusEl.textContent='Ficha carregada';root.innerHTML=`<div class="page"><section class="card"><div class="profile"><div class="avatar">👤</div><div><div class="name">${esc(title(p.full_name))}</div><div class="meta">Família ${esc(p.family_code||'—')}</div><div class="tags">${flags(p).length?flags(p).map(x=>`<span class="tag on">${esc(x)}</span>`).join(''):'<span class="tag">Sem marcadores</span>'}</div></div></div><div class="grid"><div class="box"><small>Nascimento</small><b>${fmt(p.birth_date)}</b></div><div class="box"><small>Telefone</small><b>${esc(p.phone||'Sem dado')}</b></div><div class="box"><small>CNS</small><b>${esc(p.cns||'Sem dado')}</b></div><div class="box"><small>Última visita oficial</small><b>${fmt(p.last_visit)}</b></div></div><div class="address">📍 ${esc([p.street,p.number,p.neighborhood].filter(Boolean).join(', ')||'Endereço sem dado')}</div><div class="actions"><button class="btn teal" id="visit">Iniciar visita</button><button class="btn blue" id="plan">Planejar visita</button><button class="btn ghost" id="edit-cond">Editar condições</button></div></section><section class="card"><div class="title"><span>🩺 Condições registradas</span><button class="btn blue" id="edit-cond-2">Editar</button></div>${conditions.length?conditions.map(c=>`<div class="cond"><b>${esc(c.condition_name)}</b><span>${esc((c.clinical_status||c.status||'registrada'))}${c.onset_on?` · desde ${fmt(c.onset_on)}`:''}${c.ended_on?` · até ${fmt(c.ended_on)}`:''}</span></div>`).join(''):'<div class="empty">Nenhuma condição estruturada registrada.</div>'}</section><section class="card"><div class="title">🕘 Visitas recentes</div>${visits.length?visits.map(v=>`<div class="history"><b>${fmt(v.visit_date)} · ${esc(v.status||'')}</b><span>${esc(v.visit_type||'domiciliar')}${v.official?' · oficial':' · registro local'}</span>${v.notes?`<div class="meta">${esc(v.notes)}</div>`:''}</div>`).join(''):'<div class="empty">Sem visitas associadas.</div>'}</section></div>`;
 document.getElementById('visit').onclick=()=>{const u=new URL('../acs-visita-campo/',location.href);u.searchParams.set('person',p.id);u.searchParams.set('source','Ficha do paciente');location.assign(u.href)};
 document.getElementById('plan').onclick=openPlan;
 document.getElementById('edit-cond').onclick=document.getElementById('edit-cond-2').onclick=openConditions;
}
function errorView(e){statusEl.textContent='Não foi possível abrir';root.innerHTML=`<div class="error"><h2>Não foi possível abrir a ficha</h2><p>${esc(e?.name==='AbortError'?'A conexão demorou além do esperado.':e?.message||'Falha de comunicação.')}</p><button class="btn blue" id="retry">Tentar novamente</button></div>`;document.getElementById('retry').onclick=load}
async function load(){if(!key||!UUID.test(personId)){return errorView(new Error('Paciente ou acesso inválido.'))}statusEl.textContent='Carregando…';root.innerHTML='<section class="boot"><div class="spinner"></div><h2>Abrindo ficha…</h2><p>Carregando uma única consulta.</p></section>';try{detail=await request(FAST,'detail',{params:{id:personId}});if(!detail.person)throw new Error('Paciente não localizado.');render()}catch(e){errorView(e)}}
const PRESETS=[['hipertensao','Hipertensão'],['diabetes','Diabetes'],['gestante','Gestação'],['acamado','Acamado'],['domiciliado','Domiciliado'],['deficiencia','Deficiência / reabilitação'],['cancer','Câncer'],['saude_mental','Saúde mental'],['asma','Asma'],['dpoc','DPOC / enfisema'],['doenca_respiratoria','Doença respiratória'],['doenca_cardiaca','Doença cardíaca'],['problema_rins','Problema nos rins'],['tuberculose','Tuberculose'],['hanseniase','Hanseníase'],['avc','AVC / derrame'],['infarto','Infarto'],['tabagista','Tabagismo'],['alcool','Uso de álcool'],['outras_drogas','Outras drogas']];
const LABEL=Object.fromEntries(PRESETS);
function allowed(k,a){if(k==='gestante'&&a!=null&&a<10)return false;if(['tabagista','alcool','outras_drogas'].includes(k)&&a!=null&&a<10)return false;return true}
async function openConditions(){try{condData=await request(CONDITIONS,'current',{params:{person_id:personId}});renderConditions()}catch(e){toast(e.message||'Não foi possível carregar as condições.')}}
function renderConditions(){document.querySelector('.modal-back')?.remove();const a=condData.age_years??age(detail.person.birth_date),act=(condData.conditions||[]).filter(active);const back=document.createElement('div');back.className='modal-back';back.innerHTML=`<div class="modal"><div class="modal-head"><div><h2 style="margin:0">Condições atuais</h2><div class="meta">${esc(title(detail.person.full_name))} · ${a!=null?a+' anos':'idade não informada'}</div></div><button class="close" id="mc-close">×</button></div><p>Para retirar, toque no ×. O histórico fica preservado.</p><div class="active-list">${act.length?act.map(c=>`<span class="active-chip">${esc(c.condition_name)} <button data-remove="${esc(c.condition_key||'')}">×</button></span>`).join(''):'<span class="empty">Nenhuma condição ativa.</span>'}</div><label class="meta" style="display:block;margin-top:16px">Origem da informação</label><select class="source" id="source"><option value="autorreferida">Cidadão/familiar informou</option><option value="documentada">Documento, receita ou laudo</option><option value="informada_equipe">Informada pela equipe</option></select><div class="title" style="font-size:18px">Adicionar condição</div><div class="preset-grid">${PRESETS.filter(([k])=>allowed(k,a)).map(([k,l])=>{const on=act.some(c=>c.condition_key===k);return `<button class="preset" data-add="${k}" ${on?'disabled':''}>${on?'✓ ':'+ '}${esc(l)}</button>`}).join('')}</div></div>`;document.body.appendChild(back);document.getElementById('mc-close').onclick=()=>back.remove();document.getElementById('source').value=source;document.getElementById('source').onchange=e=>source=e.target.value;back.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>setCondition(b.dataset.add,true));back.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>setCondition(b.dataset.remove,false))}
async function setCondition(k,wanted){if(!k)return;try{const out=await request(CONDITIONS,'set_condition',{method:'POST',body:{person_id:personId,condition_key:k,condition_name:LABEL[k]||k,active:wanted,verification_status:source}});condData=out;toast(wanted?'Condição adicionada.':'Condição retirada das atuais.');detail=await request(FAST,'detail',{params:{id:personId}});render();renderConditions()}catch(e){toast(e.message||'Não foi possível atualizar.')}}
function openPlan(){const p=detail.person,back=document.createElement('div');back.className='modal-back';back.innerHTML=`<div class="modal"><div class="modal-head"><h2>Planejar visita</h2><button class="close" id="pc-close">×</button></div><label class="meta">Data</label><input id="pdate" class="source" type="date" value="${new Date().toISOString().slice(0,10)}"><label class="meta">Motivo</label><input id="preason" class="source" value="Visita domiciliar"><button class="btn teal" id="psave" style="width:100%">Adicionar ao roteiro</button></div>`;document.body.appendChild(back);document.getElementById('pc-close').onclick=()=>back.remove();document.getElementById('psave').onclick=async()=>{try{await request(VISIT_API,'save_agenda',{method:'POST',body:{person_id:p.id,scheduled_date:document.getElementById('pdate').value,reason:document.getElementById('preason').value,priority_block:'rotina'}});toast('Visita adicionada ao roteiro.');back.remove()}catch(e){toast(e.message||'Não foi possível planejar.')}}}
document.getElementById('back').onclick=()=>{if(history.length>1)history.back();else location.assign('../esf06-visita/?v=22')};
load();
})();