(()=>{'use strict';
const nativeFetch=window.fetch.bind(window),DB='esf06-field-v38',VER=1,QUEUE=new Set(['save_visit_group','save_form','complete_agenda']);let dbp=null,syncing=false;
function key(){return new URL(location.href).searchParams.get('k')||localStorage.getItem('esf06_visit_key')||''}
function openDb(){if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('outbox'))d.createObjectStore('outbox',{keyPath:'id'});if(!d.objectStoreNames.contains('cache'))d.createObjectStore('cache',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbp}
async function put(store,v){const d=await openDb();return new Promise((res,rej)=>{const q=d.transaction(store,'readwrite').objectStore(store).put(v);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function del(store,id){const d=await openDb();return new Promise((res,rej)=>{const q=d.transaction(store,'readwrite').objectStore(store).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function get(store,id){const d=await openDb();return new Promise((res,rej)=>{const q=d.transaction(store,'readonly').objectStore(store).get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function all(store){const d=await openDb();return new Promise((res,rej)=>{const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
function requestInfo(input,init={}){try{const raw=typeof input==='string'?input:input.url,u=new URL(raw,location.href);if(u.hostname!=='pvwqxpqetdxtmqqypqjk.supabase.co')return null;const api=u.searchParams.get('api')||'',method=String(init.method||(typeof input!=='string'&&input.method)||'GET').toUpperCase();return{u,api,method}}catch{return null}}
function cacheId(u){const x=new URL(u);x.searchParams.delete('k');return x.toString()}
async function cacheResponse(u,r){try{const text=await r.clone().text();await put('cache',{id:cacheId(u),status:r.status,headers:[...r.headers.entries()],text,saved_at:Date.now()});const rows=await all('cache');if(rows.length>60){rows.sort((a,b)=>a.saved_at-b.saved_at);for(const x of rows.slice(0,rows.length-60))await del('cache',x.id)}}catch(e){console.warn('cache field',e)}}
async function cachedResponse(u){try{const x=await get('cache',cacheId(u));if(!x)return null;return new Response(x.text,{status:x.status||200,headers:x.headers||[['content-type','application/json']]})}catch{return null}}
async function queue(api,init){let body={};try{body=JSON.parse(String(init.body||'{}'))}catch{}const stable=body.id||body.group_id||body.person_id||crypto.randomUUID(),id=`${api}:${stable}`;await put('outbox',{id,api,body,created_at:Date.now()});status();return new Response(JSON.stringify({queued:true,offline:true}),{status:200,headers:{'content-type':'application/json'}})}
window.fetch=async function(input,init={}){const info=requestInfo(input,init);if(!info)return nativeFetch(input,init);if(info.method==='POST'&&QUEUE.has(info.api)){if(!navigator.onLine)return queue(info.api,init);try{return await nativeFetch(input,init)}catch(e){if(e?.name==='AbortError'||e instanceof TypeError)return queue(info.api,init);throw e}}
if(info.method==='GET'&&(info.api==='detail'||info.api==='family_members')){try{const r=await nativeFetch(input,init);if(r.ok)cacheResponse(info.u,r);return r}catch(e){const c=await cachedResponse(info.u);if(c)return c;throw e}}
return nativeFetch(input,init)};
async function count(){try{return(await all('outbox')).length}catch{return 0}}
async function status(){const n=await count();let el=document.getElementById('field-sync-v38');if(!el){el=document.createElement('div');el.id='field-sync-v38';document.body.appendChild(el)}if(!navigator.onLine){el.className='field-sync-v38 off';el.textContent=n?`📡 Offline · ${n} registro(s) salvo(s) no aparelho`:'📡 Offline · os pacientes já sincronizados continuam disponíveis'}else if(n){el.className='field-sync-v38 wait';el.textContent=`⏳ ${n} registro(s) aguardando envio ao Supabase`}else{el.className='field-sync-v38 ok';el.textContent='✓ Sincronizado com Supabase';clearTimeout(status.t);status.t=setTimeout(()=>el.classList.add('fade'),2400)}}
async function sync(){if(syncing||!navigator.onLine)return;syncing=true;try{const rows=(await all('outbox')).sort((a,b)=>a.created_at-b.created_at);for(const x of rows){try{const u=new URL('https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-visita-api');u.searchParams.set('api',x.api);u.searchParams.set('k',key());const r=await nativeFetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x.body),cache:'no-store'});if(!r.ok)break;await del('outbox',x.id)}catch{break}}}finally{syncing=false;status()}}
window.addEventListener('online',()=>{status();sync()});window.addEventListener('offline',status);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});setInterval(sync,60000);setTimeout(()=>{status();sync()},250);
window.ACSFieldOfflineV38={sync,count,status};
})();