(()=>{'use strict';
const API='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-next-v37';
const qs=new URL(location.href).searchParams;let key=qs.get('k')||localStorage.getItem('esf06_lab_key')||localStorage.getItem('esf06_visit_key')||'';if(qs.get('k'))localStorage.setItem('esf06_lab_key',key);
const app=document.getElementById('app'),net=document.getElementById('net');const S={page:'home',dash:null,people:null,quality:null,followups:null,referrals:null,vaccines:null,territory:null,person:null,routeDate:new Date().toISOString().slice(0,10),preview:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{if(!v)return'—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v)};
const title=v=>String(v||'').toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase());
function toast(msg,type='ok'){const t=document.getElementById('toast');t.textContent=msg;t.className='toast '+type;clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast hidden',3500)}
async function api(name,{params={},method='GET',body}={}){const u=new URL(API);u.searchParams.set('api',name);u.searchParams.set('k',key);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(j.error||`Erro ${r.status}`);return j}
function modal(html){const b=document.createElement('div');b.className='modal-back';b.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(b);b.querySelector('[data-close]')?.addEventListener('click',()=>b.remove());b.addEventListener('click',e=>{if(e.target===b)b.remove()});return b}
function shell(inner){app.innerHTML=`<div class="page"><div class="lab-banner">🧪 <b>Ambiente de laboratório.</b> Tudo aqui usa pessoas e famílias fictícias no schema <code>esf06_next</code>. O cadastro real da ESF06 não é alterado.</div>${inner}<div class="footer-space"></div></div>`}
function back(label='← Voltar'){return `<button class="btn soft back" data-back>${label}</button>`}
function bindBack(){document.querySelector('[data-back]')?.addEventListener('click',()=>go('home'))}
function go(p,arg){S.page=p;if(p==='home')return home();if(p==='quality')return qualityPage();if(p==='followups')return followupsPage();if(p==='referrals')return referralsPage();if(p==='vaccines')return vaccinesPage();if(p==='territory')return territoryPage();if(p==='route')return routePage();if(p==='sync')return syncPage();if(p==='people')return peoplePage();if(p==='person')return personPage(arg)}
async function ensurePeople(){if(!S.people)S.people=(await api('people')).rows;return S.people}
function netStatus(){const on=navigator.onLine;net.textContent=on?'online · laboratório isolado':'offline · usando fila local';net.parentElement?.classList.toggle('offline',!on)}
window.addEventListener('online',()=>{netStatus();syncQueue(true)});window.addEventListener('offline',netStatus);
document.getElementById('home').onclick=()=>go('home');

async function home(){try{S.dash=(await api('dashboard')).dashboard;const d=S.dash;shell(`<div class="kpis"><div class="kpi"><b>${d.people}</b><span>Pessoas fictícias</span></div><div class="kpi"><b>${d.families}</b><span>Famílias fictícias</span></div><div class="kpi"><b>${d.quality.total}</b><span>Alertas cadastrais</span></div><div class="kpi"><b>${d.open_referrals}</b><span>Encaminhamentos abertos</span></div><div class="kpi"><b>${d.vaccine_pending}</b><span>Pendências vacinais</span></div><div class="kpi"><b>${d.locations_confirmed}</b><span>Localizações confirmadas</span></div></div><div class="section">MÓDULOS DA V37</div><div class="grid">${[
['quality','🧹','Qualidade cadastral','Busca automaticamente dados faltantes e divergências.'],['people','👤','Ficha Mestre','Linha do tempo longitudinal por pessoa.'],['followups','🩺','Acompanhamentos','HAS, diabetes, gestação, crianças, idosos e domiciliados.'],['referrals','↗️','Encaminhamentos','Solicitado → entregue → agendado → realizado → resultado → retorno.'],['vaccines','💉','Vacinação','Doses documentadas e pendências separadas.'],['territory','📍','Território','Coordenada confirmada e referência por família.'],['route','🗺️','Roteiro inteligente','Só calcula após clique e exige visita manual primeiro.'],['sync','☁️','Modo campo/offline','Fila local, sincronização e teste de reenvio.']
].map(x=>`<button class="tile" data-go="${x[0]}"><span class="ico">${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small><em>Abrir →</em></button>`).join('')}</div>`);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}catch(e){shell(`<div class="card"><h2>Não consegui abrir o laboratório</h2><p>${esc(e.message)}</p></div>`)} }

async function qualityPage(){shell(`${back()}<div class="card"><div class="title"><div><h2>🧹 Cadastro para corrigir</h2><p>Problemas calculados ao vivo. Resolver um alerta registra a decisão no laboratório.</p></div></div><div id="ql"><div class="boot"><div class="spinner"></div></div></div></div>`);bindBack();try{S.quality=(await api('quality')).rows;renderQuality()}catch(e){document.getElementById('ql').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderQuality(){const rows=S.quality||[],g={alta:rows.filter(x=>x.severity==='alta').length,media:rows.filter(x=>x.severity!=='alta').length};document.getElementById('ql').innerHTML=`<div class="kpis"><div class="kpi"><b>${rows.length}</b><span>Alertas abertos</span></div><div class="kpi"><b>${g.alta}</b><span>Prioridade alta</span></div><div class="kpi"><b>${g.media}</b><span>Demais alertas</span></div></div>${rows.length?rows.map(x=>`<div class="row"><div class="row-top"><div><b>${esc(title(x.name))}</b><p>${esc(x.family_code)} · ${esc(x.label)}</p></div><span class="badge ${x.severity==='alta'?'bad':'warn'}">${esc(x.severity)}</span></div><button class="btn teal" data-resolve='${esc(JSON.stringify({entity_type:x.entity_type,entity_id:x.entity_id,issue_key:x.issue_key}))}'>Marcar resolvido</button></div>`).join(''):'<div class="empty">Nenhum alerta aberto.</div>'}`;document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{const body=JSON.parse(b.dataset.resolve);try{await api('quality_resolve',{method:'POST',body:{...body,status:'resolvido',notes:'Resolvido no laboratório v37'}});toast('Alerta resolvido no laboratório.');S.quality=(await api('quality')).rows;renderQuality()}catch(e){toast(e.message,'err')}})}

async function peoplePage(){shell(`${back()}<div class="card"><div class="title"><div><h2>👤 Ficha Mestre</h2><p>Abra uma pessoa fictícia para ver a linha do tempo longitudinal.</p></div></div><div class="search">⌕ <input id="pq" placeholder="Buscar nome ou família"></div><div id="pl"></div></div>`);bindBack();const rows=await ensurePeople();const render=()=>{const q=(document.getElementById('pq').value||'').toLowerCase(),r=rows.filter(x=>`${x.full_name} ${x.family_code}`.toLowerCase().includes(q));document.getElementById('pl').innerHTML=r.map(x=>`<button class="row block" style="width:100%;text-align:left" data-person="${x.id}"><b>${esc(title(x.full_name))}</b><p>${esc(x.family_code)} · ${x.age==null?'idade não cadastrada':x.age+' anos'} · ${esc([x.street,x.number].filter(Boolean).join(', ')||'endereço incompleto')}</p></button>`).join('')};render();document.getElementById('pq').oninput=render;document.getElementById('pl').onclick=e=>{const b=e.target.closest('[data-person]');if(b)go('person',b.dataset.person)}}
async function personPage(id){shell(`${back('← Pessoas')}<div id="person"><div class="boot"><div class="spinner"></div></div></div>`);document.querySelector('[data-back]').onclick=()=>go('people');try{S.person=await api('person',{params:{id}});const d=S.person,p=d.person;shell(`${back('← Pessoas')}<div class="card"><div class="profile"><div class="avatar">👤</div><div><h2>${esc(title(p.full_name))}</h2><div class="meta">Família ${esc(p.family_code)} · ${p.age==null?'idade não cadastrada':p.age+' anos'}</div><div class="badges">${Object.entries(p.flags||{}).filter(([,v])=>v===true).map(([k])=>`<span class="badge ok">${esc(k)}</span>`).join('')}</div></div></div><div class="info-grid"><div class="info"><small>Nascimento</small><b>${fmt(p.birth_date)}</b></div><div class="info"><small>Telefone</small><b>${esc(p.phone||'Sem dado')}</b></div><div class="info"><small>CNS</small><b>${esc(p.cns||'Sem dado')}</b></div><div class="info"><small>Risco familiar</small><b>${esc(p.risk)}</b></div></div><p class="meta">📍 ${esc([p.street,p.number,p.neighborhood].filter(Boolean).join(', ')||'Endereço incompleto')}</p><div class="two"><button class="btn teal" id="test-visit">Registrar visita teste</button><button class="btn blue" id="test-plan">Inserir visita manual no roteiro</button></div></div><div class="card"><div class="title"><h3>🕘 Linha do tempo</h3></div><div class="timeline">${d.timeline.length?d.timeline.map(x=>`<div class="event"><b>${fmt(x.date)} · ${esc(x.title)}</b><small>${esc(x.kind)}${x.detail?' · '+x.detail:''}</small></div>`).join(''):'<div class="empty">Sem eventos.</div>'}</div></div>`);document.querySelector('[data-back]').onclick=()=>go('people');document.getElementById('test-visit').onclick=()=>visitModal(p);document.getElementById('test-plan').onclick=()=>planModal(p)}catch(e){toast(e.message,'err')}}
function visitModal(p){const m=modal(`<div class="modal-head"><h2>Visita teste</h2><button class="close" data-close>×</button></div><div class="form"><label>Data</label><input id="vd" type="date" value="${new Date().toISOString().slice(0,10)}"><label>Desfecho</label><select id="vo"><option>Visita realizada</option><option>Ausente</option><option>Visita recusada</option></select><label>Observações</label><textarea id="vn" placeholder="Somente teste"></textarea><button class="btn teal block" id="vs">Salvar / colocar na fila</button></div>`);m.querySelector('#vs').onclick=async()=>{const group=crypto.randomUUID(),form=crypto.randomUUID(),date=m.querySelector('#vd').value,outcome=m.querySelector('#vo').value,notes=m.querySelector('#vn').value;const ops=[{api:'save_visit_group',body:{id:group,family_id:p.family_id,primary_person_id:p.id,visit_date:date,visit_time:new Date().toTimeString().slice(0,5),visit_scope:'cidadao',general_notes:notes,status:'completed'}},{api:'save_form',body:{id:form,group_id:group,person_id:p.id,visit_date:date,visit_time:new Date().toTimeString().slice(0,5),visit_result:outcome,status:'completed',answers:{lab:true},notes,finalize:true}}];try{for(const op of ops)await sendOrQueue(op);m.remove();toast(navigator.onLine?'Visita teste sincronizada.':'Visita salva no aparelho e aguardando sincronização.');await syncBadge()}catch(e){toast(e.message,'err')}}}
function planModal(p){const m=modal(`<div class="modal-head"><h2>Visita manual</h2><button class="close" data-close>×</button></div><div class="form"><label>Data</label><input id="pd" type="date" value="${S.routeDate}"><label>Motivo</label><input id="pr" value="Visita domiciliar"><button class="btn teal block" id="ps">Inserir manualmente</button></div>`);m.querySelector('#ps').onclick=async()=>{try{if(!navigator.onLine)throw new Error('Planejamento não entra na fila offline. Conecte para inserir.');await api('agenda_add',{method:'POST',body:{date:m.querySelector('#pd').value,person_id:p.id,reason:m.querySelector('#pr').value}});m.remove();toast('Visita manual inserida.')}catch(e){toast(e.message,'err')}}}

async function followupsPage(){shell(`${back()}<div class="card"><div class="title"><div><h2>🩺 Acompanhamentos</h2><p>Condição deixa de ser só filtro e vira painel operacional.</p></div></div><div id="fu"></div></div>`);bindBack();try{S.followups=(await api('followups')).rows;document.getElementById('fu').innerHTML=S.followups.map(x=>`<div class="row"><div class="row-top"><div><b>${esc(x.label)}</b><p>${x.families_signaled} famílias sinalizadas · ${x.people_identified} pessoas identificadas</p></div><span class="badge ${x.unresolved?'bad':'ok'}">${x.unresolved} a reconciliar</span></div><div class="badges"><span class="badge warn">${x.without_visit_month} sem visita no mês</span><span class="badge">${x.open_referrals} encaminhamentos abertos</span></div></div>`).join('')}catch(e){toast(e.message,'err')}}

const order=['solicitado','entregue','agendado','realizado','resultado_recebido','retorno_concluido'];const lab={solicitado:'Solicitado',entregue:'Entregue',agendado:'Agendado',realizado:'Realizado',resultado_recebido:'Resultado recebido',retorno_concluido:'Retorno concluído',cancelado:'Cancelado'};
async function referralsPage(){shell(`${back()}<div class="card"><div class="title"><div><h2>↗️ Encaminhamentos</h2><p>Ciclo completo e auditável.</p></div></div><div id="refs"></div></div>`);bindBack();try{S.referrals=(await api('referrals')).rows;renderRefs()}catch(e){toast(e.message,'err')}}
function renderRefs(){document.getElementById('refs').innerHTML=S.referrals.map(r=>{const idx=order.indexOf(r.current_status),next=idx>=0&&idx<order.length-1?order[idx+1]:null;return `<div class="row"><div class="row-top"><div><b>${esc(title(r.full_name||'Sem pessoa'))}</b><p>${esc(r.title)} · ${esc(r.destination||'destino não informado')}</p></div><span class="badge ${r.priority==='alta'?'bad':'warn'}">${esc(lab[r.current_status]||r.current_status)}</span></div><div class="stages">${order.map((x,i)=>`<span class="stage ${i<=idx?'on':''}">${lab[x]}</span>`).join('')}</div>${r.appointment_at?`<p class="meta">🗓️ ${new Date(r.appointment_at).toLocaleString('pt-BR')}</p>`:''}<div class="two">${next?`<button class="btn teal" data-next="${r.id}" data-status="${next}">Avançar para ${lab[next]}</button>`:''}<button class="btn bad" data-cancel="${r.id}">Cancelar</button></div></div>`}).join('');document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>advanceRef(b.dataset.next,b.dataset.status));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>advanceRef(b.dataset.cancel,'cancelado'))}
async function advanceRef(id,status){try{let appointment_at=null;if(status==='agendado'){const d=prompt('Data/hora do agendamento (AAAA-MM-DDTHH:MM)','2026-08-20T09:00');if(!d)return;appointment_at=d}await api('referral_update',{method:'POST',body:{id,status,appointment_at,notes:'Etapa atualizada no laboratório'}});S.referrals=(await api('referrals')).rows;renderRefs();toast('Encaminhamento atualizado.')}catch(e){toast(e.message,'err')}}

async function vaccinesPage(){shell(`${back()}<div class="card"><div class="title"><div><h2>💉 Vacinação</h2><p>Dose documentada e pendência são registros diferentes.</p></div><button class="btn blue" id="add-dose">+ Dose</button></div><div id="vac"></div></div>`);bindBack();try{S.vaccines=await api('vaccines');renderVac();document.getElementById('add-dose').onclick=addDoseModal}catch(e){toast(e.message,'err')}}
function renderVac(){const v=S.vaccines;document.getElementById('vac').innerHTML=`<div class="section">PENDÊNCIAS VALIDADAS / A CONFIRMAR</div>${v.pending.length?v.pending.map(x=>`<div class="row"><div class="row-top"><div><b>${esc(title(x.full_name))}</b><p>${esc(x.vaccine_name)} ${esc(x.dose_label||'')}</p></div><span class="badge ${x.status==='busca_ativa'?'bad':'warn'}">${esc(x.status)}</span></div><p class="meta">Base: ${esc(x.basis)}</p><div class="two"><button class="btn teal" data-vstat="${x.id}" data-status="resolvida">Resolver</button><button class="btn soft" data-vstat="${x.id}" data-status="descartada">Descartar</button></div></div>`).join(''):'<div class="empty">Sem pendências.</div>'}<div class="section">DOSES DOCUMENTADAS</div>${v.doses.map(x=>`<div class="row"><b>${esc(title(x.full_name))}</b><p>${fmt(x.administered_on)} · ${esc(x.vaccine_name)} ${esc(x.dose_label||'')} · fonte ${esc(x.source_type)}</p></div>`).join('')}`;document.querySelectorAll('[data-vstat]').forEach(b=>b.onclick=async()=>{try{await api('vaccine_pending_update',{method:'POST',body:{id:b.dataset.vstat,status:b.dataset.status}});S.vaccines=await api('vaccines');renderVac();toast('Pendência atualizada.')}catch(e){toast(e.message,'err')}})}
async function addDoseModal(){const people=await ensurePeople();const m=modal(`<div class="modal-head"><h2>Adicionar dose documentada</h2><button class="close" data-close>×</button></div><div class="form"><label>Pessoa</label><select id="vp">${people.map(p=>`<option value="${p.id}">${esc(title(p.full_name))}</option>`).join('')}</select><label>Vacina</label><input id="vv" placeholder="Ex.: Influenza"><label>Dose</label><input id="vl" placeholder="Ex.: 1ª dose"><label>Data</label><input id="vdate" type="date"><label>Fonte</label><select id="vsrc"><option value="caderneta">Caderneta</option><option value="documento">Documento</option><option value="equipe">Equipe</option><option value="informada">Informada</option></select><button class="btn teal block" id="vsave">Salvar dose</button></div>`);m.querySelector('#vsave').onclick=async()=>{try{await api('vaccine_add',{method:'POST',body:{person_id:m.querySelector('#vp').value,vaccine_name:m.querySelector('#vv').value,dose_label:m.querySelector('#vl').value,administered_on:m.querySelector('#vdate').value||null,source_type:m.querySelector('#vsrc').value,verification_status:'documentado'}});m.remove();S.vaccines=await api('vaccines');renderVac();toast('Dose adicionada no laboratório.')}catch(e){toast(e.message,'err')}}}

async function territoryPage(){shell(`${back()}<div class="card"><div class="title"><div><h2>📍 Território inteligente</h2><p>Coordenadas só são gravadas quando você confirma.</p></div></div><div id="ter"></div></div>`);bindBack();try{S.territory=(await api('territory')).rows;renderTerritory()}catch(e){toast(e.message,'err')}}
function renderTerritory(){document.getElementById('ter').innerHTML=S.territory.map(x=>`<div class="row"><div class="row-top"><div><b>${esc(x.family_code)} · ${esc(title(x.responsible_name))}</b><p>${esc([x.street,x.number,x.neighborhood].filter(Boolean).join(', ')||'Endereço incompleto')}</p></div><span class="badge ${x.location_status==='confirmada'?'ok':'warn'}">${esc(x.location_status||'não confirmada')}</span></div>${x.latitude!=null?`<p class="meta">${Number(x.latitude).toFixed(5)}, ${Number(x.longitude).toFixed(5)} ${x.accuracy_m?'· ±'+Math.round(x.accuracy_m)+'m':''}</p>`:''}<button class="btn blue" data-geo="${x.family_id}">Confirmar minha posição nesta família</button></div>`).join('');document.querySelectorAll('[data-geo]').forEach(b=>b.onclick=()=>captureGeo(b.dataset.geo))}
function captureGeo(family_id){if(!navigator.geolocation)return toast('Geolocalização não disponível.','err');navigator.geolocation.getCurrentPosition(async p=>{try{await api('territory_save',{method:'POST',body:{family_id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,location_status:'confirmada',reference_text:'Confirmada no laboratório'}});S.territory=(await api('territory')).rows;renderTerritory();toast('Localização confirmada no laboratório.')}catch(e){toast(e.message,'err')}},e=>toast('Não foi possível obter a localização: '+e.message,'err'),{enableHighAccuracy:true,timeout:10000})}

async function routePage(){await ensurePeople();shell(`${back()}<div class="card"><div class="title"><div><h2>🗺️ Roteiro inteligente</h2><p>Nunca sugere sozinho: primeiro você insere visita, depois toca em calcular.</p></div></div><div class="form"><label>Data</label><input id="rd" type="date" value="${S.routeDate}"></div><button class="btn blue block" id="manual">+ Inserir visita manual</button><div id="route"></div><button class="btn teal block" id="smart">Calcular até 5 sugestões</button><div id="preview"></div></div>`);bindBack();document.getElementById('rd').onchange=e=>{S.routeDate=e.target.value;S.preview=[];loadRoute()};document.getElementById('manual').onclick=routeManual;document.getElementById('smart').onclick=smartPreview;await loadRoute()}
async function loadRoute(){try{const r=await api('route',{params:{date:S.routeDate}});document.getElementById('route').innerHTML=`<div class="section">ROTEIRO ATUAL</div>${r.rows.length?r.rows.map((x,i)=>`<div class="row route-person"><div><b>${i+1}. ${esc(title(x.full_name))}</b><p>${esc(x.family_code)} · ${esc(x.reason)}</p></div><span class="badge ${String(x.notes||'').startsWith('[smart-confirmed]')?'ok':'warn'}">${String(x.notes||'').startsWith('[smart-confirmed]')?'inteligente confirmado':'manual'}</span></div>`).join(''):'<div class="empty">Nenhuma visita inserida.</div>'}`}catch(e){toast(e.message,'err')}}
function routeManual(){const m=modal(`<div class="modal-head"><h2>Inserir visita manual</h2><button class="close" data-close>×</button></div><div class="form"><label>Pessoa</label><select id="rp">${S.people.map(p=>`<option value="${p.id}">${esc(title(p.full_name))} · ${esc(p.family_code)}</option>`).join('')}</select><label>Motivo</label><input id="rr" value="Visita domiciliar"><button class="btn teal block" id="rs">Inserir</button></div>`);m.querySelector('#rs').onclick=async()=>{try{if(!navigator.onLine)throw new Error('Planejamento não é colocado na fila offline.');await api('agenda_add',{method:'POST',body:{date:S.routeDate,person_id:m.querySelector('#rp').value,reason:m.querySelector('#rr').value}});m.remove();S.preview=[];document.getElementById('preview').innerHTML='';await loadRoute();toast('Visita manual inserida.')}catch(e){toast(e.message,'err')}}}
async function smartPreview(){try{const r=await api('smart_preview',{params:{date:S.routeDate}});S.preview=r.rows||[];document.getElementById('preview').innerHTML=`<div class="section">PRÉVIA — NADA FOI ADICIONADO</div><p class="meta">${esc(r.message)}</p>${S.preview.map(x=>`<label class="row suggest" style="display:block"><input type="checkbox" data-smart="${x.person_id}" checked> <b>${esc(title(x.full_name))}</b><p>${esc(x.family_code)} · ${x.distance_m==null?'sem coordenada comparável':x.distance_m+' m da visita manual mais próxima'} · score ${x.score}</p></label>`).join('')}${S.preview.length?'<button class="btn teal block" id="accept-smart">Adicionar selecionadas</button>':''}`;document.getElementById('accept-smart')?.addEventListener('click',acceptSmart)}catch(e){toast(e.message,'err')}}
async function acceptSmart(){try{const ids=[...document.querySelectorAll('[data-smart]:checked')].map(x=>x.dataset.smart);await api('smart_accept',{method:'POST',body:{date:S.routeDate,explicit:true,person_ids:ids}});S.preview=[];document.getElementById('preview').innerHTML='';await loadRoute();toast('Sugestões adicionadas somente após confirmação.')}catch(e){toast(e.message,'err')}}

function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('esf06_lab_v37',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('queue'))r.result.createObjectStore('queue',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function qAll(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('queue','readonly'),r=tx.objectStore('queue').getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function qPut(x){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('queue','readwrite');tx.objectStore('queue').put(x);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function qDel(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('queue','readwrite');tx.objectStore('queue').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function sendOrQueue(op){if(navigator.onLine){try{return await api(op.api,{method:'POST',body:op.body})}catch(e){await qPut({id:crypto.randomUUID(),...op,created_at:new Date().toISOString(),last_error:e.message});return null}}await qPut({id:crypto.randomUUID(),...op,created_at:new Date().toISOString(),last_error:'offline'});return null}
async function syncQueue(silent=false){if(!navigator.onLine)return;const rows=await qAll();let ok=0;for(const x of rows){try{await api(x.api,{method:'POST',body:x.body});await qDel(x.id);ok++}catch(e){x.last_error=e.message;await qPut(x)}}if(ok&&!silent)toast(`${ok} operação(ões) sincronizada(s).`);await syncBadge();if(S.page==='sync')syncPage()}
async function syncBadge(){const q=await qAll();net.textContent=(navigator.onLine?'online':'offline')+` · ${q.length} na fila`}
async function syncPage(){const q=await qAll();shell(`${back()}<div class="card"><div class="title"><div><h2>☁️ Modo campo/offline</h2><p>A fila automática aceita somente operações idempotentes de visita.</p></div></div><div class="status ${navigator.onLine?'':'off'}"><span class="dot"></span><b>${navigator.onLine?'Conectado ao Supabase':'Sem conexão'}</b><span class="queue">${q.length} na fila</span></div><div class="row"><b>O que entra na fila</b><p>✓ save_visit_group · ✓ save_form. IDs UUID impedem duplicação no reenvio.</p></div><div class="row"><b>O que NÃO entra</b><p>✕ agendamento manual · ✕ Roteiro inteligente · ✕ alterações que possam mudar planejamento sem ação explícita.</p></div><button class="btn teal block" id="syncnow" ${navigator.onLine?'':'disabled'}>Sincronizar agora</button><div class="section">FILA LOCAL</div>${q.length?q.map(x=>`<div class="row"><b>${esc(x.api)}</b><p>${new Date(x.created_at).toLocaleString('pt-BR')} · ${esc(x.last_error||'aguardando')}</p></div>`).join(''):'<div class="empty">Fila vazia.</div>'}</div>`);bindBack();document.getElementById('syncnow').onclick=()=>syncQueue(false)}

async function init(){netStatus();if(!key){shell(`<div class="card"><h2>Link do laboratório</h2><p>Abra o laboratório pelo link que contém sua chave de acesso. A chave só autoriza a API; os dados exibidos aqui são fictícios.</p></div>`);return}try{await api('health');await syncQueue(true);await home();await syncBadge();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=37').catch(()=>{})}catch(e){shell(`<div class="card"><h2>Laboratório indisponível</h2><p>${esc(e.message)}</p></div>`)}}
init();
})();