(()=>{'use strict';
const BASE='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1/acs-reports-v2';
const app=document.getElementById('app');
if(!app)return;
const $=(sel,root=document)=>root.querySelector(sel);
const $$=(sel,root=document)=>[...root.querySelectorAll(sel)];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const T=s=>String(s||'').toLocaleLowerCase('pt-BR').replace(/(^|\s|[-'’])\p{L}/gu,m=>m.toLocaleUpperCase('pt-BR'));
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>localDate();
const monthStart=()=>today().slice(0,8)+'01';
const shiftDate=(iso,{days=0,months=0}={})=>{const d=new Date(iso+'T12:00:00');if(months)d.setMonth(d.getMonth()+months);if(days)d.setDate(d.getDate()+days);return localDate(d)};
const F=s=>{if(!s)return'—';const p=String(s).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(s)};
const fmtPhone=s=>{const d=String(s||'').replace(/\D/g,'');const n=d.startsWith('55')&&d.length>=12?d.slice(2):d;if(n.length===11)return`(${n.slice(0,2)}) ${n.slice(2,7)}-${n.slice(7)}`;if(n.length===10)return`(${n.slice(0,2)}) ${n.slice(2,6)}-${n.slice(6)}`;return s||'—'};
const houseNo=s=>{const m=String(s||'').match(/\d+/);return m?Number(m[0]):999999};
const fmtWalk=m=>m==null?'—':Number(m)<1000?`${Math.round(Number(m))} m`:`${(Number(m)/1000).toFixed(1).replace('.',',')} km`;
const ACCESS=()=>new URL(location.href).searchParams.get('k')||localStorage.getItem('esf06_visit_key')||'';
const STORE='esf06_reports_v3_state';
const DEFAULT={mode:'families',preset:'coverage',q:'',street:'all',period:'month',start:monthStart(),end:today(),visit:'all',condition:'all',age:'all',ageMin:'',ageMax:'',sex:'all',role:'all',risk:'all',pbf:'all',recad:'all',phone:'all',geo:'all',distance:'all',source:'all',priority:'all',quality:'all',sort:'street',group:'none',limit:100};
let remembered={};try{remembered=JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch{}
const state={...DEFAULT,...remembered,snapshot:null,visits:[],visitsKey:'',loading:false,error:'',generatedAt:null};
const MODES={families:['🏠','Famílias'],people:['👤','Pessoas'],visits:['🗓️','Visitas'],pbf:['💳','Bolsa Família'],recad:['🏘️','Recadastro'],tasks:['✅','Pendências']};
const PRESETS=[['coverage','Cobertura','families'],['conditions','Condições','people'],['pbf','Bolsa Família','pbf'],['recad','Recadastro','recad'],['tasks','Pendências','tasks'],['visits','Visitas','visits']];
const CONDITIONS=[['all','Todas as condições'],['hipertenso','Hipertensão'],['diabetico','Diabetes'],['acamado','Acamado'],['domiciliado','Domiciliado'],['gestante','Gestante'],['puerpera','Puérpera'],['oncologia','Oncologia / câncer'],['saudeMental','Saúde mental'],['asma','Asma / respiratório'],['pcd','PCD'],['tabagista','Tabagismo']];
const AGES=[['all','Todas as idades'],['u2','Menor de 2 anos'],['2_6','2 a 6 anos'],['7_17','7 a 17 anos'],['18_59','18 a 59 anos'],['60p','60 anos ou mais'],['65p','65 anos ou mais'],['unknown','Idade não informada'],['custom','Outra faixa…']];
const VISITS=[['all','Qualquer situação'],['visited','Visitada no período'],['not_visited','Sem visita no período'],['official','Com visita oficial'],['local_only','Somente registro local']];
function remember(){const x={};for(const k of Object.keys(DEFAULT))x[k]=state[k];localStorage.setItem(STORE,JSON.stringify(x))}
function reportActive(){return !!$('[data-nav="reports"]')?.classList.contains('on')}
function injectStyle(){if($('#reports-r3-style'))return;const s=document.createElement('style');s.id='reports-r3-style';s.textContent=`
#reports-v3{--line:#dfe6ed;--muted:#708096;--blue:#246bfd;--teal:#079b88;--ink:#17243b}
.r3-hero{background:linear-gradient(135deg,#082a4b,#0f6e75);border-radius:22px;padding:18px;color:#fff;margin-bottom:12px;box-shadow:0 9px 30px rgba(7,26,49,.11)}
.r3-heroTop{display:flex;gap:12px;align-items:flex-start;justify-content:space-between}.r3-hero h1{font-size:25px;margin:0}.r3-hero p{margin:6px 0 0;color:#c9e3e5;line-height:1.42}.r3-updated{font-size:11px;color:#9fd3d7;margin-top:7px}
.r3-refresh{border:1px solid #ffffff45;background:#ffffff17;color:#fff;border-radius:12px;padding:10px 12px;min-height:44px;font-weight:900;white-space:nowrap}
.r3-presets{display:flex;gap:8px;overflow-x:auto;padding:1px 0 7px;scrollbar-width:none}.r3-presets::-webkit-scrollbar{display:none}.r3-preset{flex:0 0 auto;border:1px solid var(--line);background:#fff;color:#526176;border-radius:999px;padding:10px 13px;min-height:44px;font-weight:850}.r3-preset.on{background:#1e6df4;border-color:#1e6df4;color:#fff}
.r3-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:9px 0 12px}.r3-kpi{background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px;min-width:0}.r3-kpi b{display:block;font-size:24px;line-height:1.08}.r3-kpi span{display:block;font-size:11px;color:var(--muted);margin-top:4px}.r3-kpi.ok{background:#edf9f2}.r3-kpi.warn{background:#fff7dd}.r3-kpi.bad{background:#fff0f0}
.r3-card{background:#fff;border:1px solid var(--line);border-radius:19px;padding:14px;margin-bottom:11px;box-shadow:0 4px 18px rgba(16,35,58,.04)}.r3-card h2{font-size:17px;margin:0 0 9px}.r3-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.r3-field label{display:block;font-size:11px;font-weight:900;color:#526176;margin:0 0 5px}.r3-field input,.r3-field select{width:100%;min-height:44px;border:1px solid #d9e1e9;border-radius:12px;padding:9px 10px;background:#fff;color:var(--ink)}.r3-search{grid-column:span 2}.r3-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.r3-btn{border:0;border-radius:12px;padding:10px 12px;min-height:44px;font-weight:900}.r3-btn.primary{background:var(--blue);color:#fff}.r3-btn.teal{background:var(--teal);color:#fff}.r3-btn.soft{background:#eaf2ff;color:#205dc2}.r3-btn.gray{background:#eef2f6;color:#526176}.r3-btn:disabled{opacity:.45}
.r3-pills{display:flex;gap:6px;overflow-x:auto;padding-top:9px;scrollbar-width:none}.r3-pill{flex:0 0 auto;background:#eef4ff;color:#315d92;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:850}.r3-note{font-size:11px;color:var(--muted);line-height:1.4;margin-top:8px}
.r3-resultsHead{display:flex;gap:10px;align-items:flex-start;justify-content:space-between;margin-bottom:9px}.r3-resultsHead h2{margin:0;font-size:18px}.r3-resultsHead .sub{margin-top:3px}.r3-tableWrap{overflow:auto;border:1px solid #e5eaf0;border-radius:14px}.r3-table{width:100%;border-collapse:collapse;font-size:12px;min-width:860px}.r3-table th{position:sticky;top:0;background:#f7f9fc;color:#526176;text-align:left;padding:9px 8px;border-bottom:1px solid #e5eaf0;z-index:1}.r3-table td{padding:9px 8px;border-bottom:1px solid #edf1f4;vertical-align:top}.r3-table tbody tr:hover{background:#f8fbff}.r3-group{background:#f1f5f9!important;color:#475569;font-weight:900;font-size:11px}.r3-mobile{display:none}.r3-mcard{border:1px solid #e2e8f0;border-left:5px solid #8bb4ff;border-radius:15px;padding:11px;margin-bottom:8px;background:#fff}.r3-mcard h3{font-size:15px;margin:0 0 4px}.r3-mcard .meta{font-size:12px;color:#66768b;line-height:1.45}.r3-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.r3-tag{font-size:10px;font-weight:900;border-radius:999px;padding:4px 7px;background:#eef2f6;color:#425169}.r3-tag.ok{background:#dff4e8;color:#176e4d}.r3-tag.warn{background:#fff0cf;color:#805700}.r3-tag.bad{background:#fbe0e0;color:#a52f35}
.r3-bars{display:grid;gap:7px}.r3-bar{display:grid;grid-template-columns:minmax(105px,1fr) 2fr 34px;gap:8px;align-items:center;font-size:11px}.r3-track{height:8px;background:#edf1f4;border-radius:999px;overflow:hidden}.r3-fill{height:100%;background:#079b88;border-radius:999px}.r3-progress{height:7px;background:#edf1f4;border-radius:99px;overflow:hidden;margin-top:5px}.r3-progress span{display:block;height:100%;background:#079b88}.r3-empty{padding:28px 16px;text-align:center;background:#f7f9fb;border-radius:14px;color:var(--muted)}.r3-loading{padding:26px;text-align:center;color:#64748b}.r3-error{background:#fff0f0;color:#9d3030;border-radius:13px;padding:12px;font-weight:800;margin-bottom:10px}.r3-hidden{display:none!important}
@media(max-width:760px){.r3-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.r3-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.r3-search{grid-column:span 2}.r3-tableWrap{display:none}.r3-mobile{display:block}.r3-resultsHead{display:block}.r3-resultsHead .r3-actions{margin-top:9px}.r3-heroTop{display:block}.r3-refresh{margin-top:10px}}
@media(max-width:430px){.r3-grid{grid-template-columns:1fr}.r3-search{grid-column:auto}.r3-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media print{header,nav,.r3-presets,.r3-filters,.r3-actions,.r3-refresh,.r3-barsCard{display:none!important}body{padding:0!important;background:#fff!important}main{max-width:none!important;padding:0!important}.r3-hero{background:#fff!important;color:#111!important;box-shadow:none!important;padding:0 0 12px!important}.r3-hero p,.r3-updated{color:#444!important}.r3-card{border:0!important;box-shadow:none!important;padding:0!important}.r3-tableWrap{display:block!important;overflow:visible!important;border:0!important}.r3-table{min-width:0!important;font-size:9px!important}.r3-mobile{display:none!important}}
`;document.head.appendChild(s)}
async function api(name,params={}){const u=new URL(BASE);u.searchParams.set('api',name);u.searchParams.set('k',ACCESS());u.searchParams.set('_',Date.now());for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v));const r=await fetch(u,{cache:'no-store'});const j=await r.json().catch(()=>({error:'Resposta inválida do servidor'}));if(!r.ok)throw new Error(j.error||'Falha ao gerar relatório');return j}
function period(){if(state.period==='today')return[today(),today()];if(state.period==='7')return[shiftDate(today(),{days:-6}),today()];if(state.period==='30')return[shiftDate(today(),{days:-29}),today()];if(state.period==='3m')return[shiftDate(today(),{months:-3,days:1}),today()];if(state.period==='6m')return[shiftDate(today(),{months:-6,days:1}),today()];if(state.period==='12m')return[shiftDate(today(),{months:-12,days:1}),today()];if(state.period==='month')return[monthStart(),today()];return[state.start||monthStart(),state.end||today()]}
async function ensureVisits(force=false){if(!state.snapshot)return;const[start,end]=period(),key=`${start}|${end}`;if(!force&&state.visitsKey===key)return;const j=await api('visits',{start,end});state.visits=j.rows||[];state.visitsKey=key}
async function load(force=false){if(state.snapshot&&!force)return;state.loading=true;state.error='';draw();try{const j=await api('snapshot');state.snapshot=j;state.generatedAt=j.generated_at||new Date().toISOString();state.visitsKey='';await ensureVisits(true)}catch(e){state.error=e.message||'Falha ao carregar relatórios'}finally{state.loading=false;draw()}}
function famMap(){return new Map((state.snapshot?.families||[]).map(f=>[String(f.family_id),f]))}
function membersMap(){const m=new Map;for(const p of state.snapshot?.people||[]){const k=String(p.family_id);if(!m.has(k))m.set(k,[]);m.get(k).push(p)}return m}
function beneficiary(f){return f?.family_flags?.bolsa_familia===true||f?.bolsa_familia?.beneficiary===true}
function pbfItemKeys(f){const members=membersMap().get(String(f.family_id))||[],responsible=members.find(p=>p.role==='responsavel')||members[0]||null,gest=members.filter(p=>p.flags?.gestante===true),u7=members.filter(p=>p.age!=null&&p.age<7),school=members.filter(p=>p.age!=null&&p.age>=4&&p.age<18),out=[];if(gest.length)gest.forEach(p=>out.push(`${p.person_id}:prenatal`));else out.push('family:prenatal');if(u7.length)u7.forEach(p=>out.push(`${p.person_id}:vacinacao`));else out.push('family:vacinacao');if(u7.length)u7.forEach(p=>out.push(`${p.person_id}:nutricao`));else out.push('family:nutricao');if(school.length)school.forEach(p=>out.push(`${p.person_id}:educacao`));else out.push('family:educacao');out.push(`${responsible?.person_id||'family'}:preventivo`);return out}
function pbfSummary(f){const tr=f?.bolsa_familia||{},checks=tr.checks&&typeof tr.checks==='object'?tr.checks:{},keys=pbfItemKeys(f);let reviewed=0,pending=0,ok=0,na=0;for(const k of keys){const s=checks[k]?.status||'nao_verificado';if(s!=='nao_verificado')reviewed++;if(s==='pendente')pending++;if(s==='em_dia')ok++;if(s==='nao_se_aplica')na++}return{expected:keys.length,reviewed,pending,ok,na,notVerified:keys.length-reviewed,last:tr.last_verified_on||null,status:tr.status||null}}
function flagLabels(p){const f=p?.flags||{},map={hipertenso:'HAS',diabetico:'Diabetes',acamado:'Acamado',domiciliado:'Domiciliado',gestante:'Gestante',puerpera:'Puérpera',oncologia:'Oncologia',saudeMental:'Saúde mental',saude_mental:'Saúde mental',asma:'Asma',problema_respiratorio:'Respiratório',pcd:'PCD',tabagista:'Tabagismo'};return Object.entries(map).filter(([k])=>f[k]===true).map(([,v])=>v).filter((v,i,a)=>a.indexOf(v)===i)}
function condMatch(p,key){if(key==='all')return true;const f=p?.flags||{};if(key==='saudeMental')return f.saudeMental===true||f.saude_mental===true;if(key==='asma')return f.asma===true||f.problema_respiratorio===true;if(key==='oncologia')return f.oncologia===true||f.cancer===true;return f[key]===true}
function ageMatch(p,key){const a=p?.age;if(key==='all')return true;if(key==='unknown')return a==null;if(key==='custom'){if(a==null)return false;const min=state.ageMin===''?null:Number(state.ageMin),max=state.ageMax===''?null:Number(state.ageMax);return(min==null||a>=min)&&(max==null||a<=max)}if(a==null)return false;if(key==='u2')return a<2;if(key==='2_6')return a>=2&&a<=6;if(key==='7_17')return a>=7&&a<=17;if(key==='18_59')return a>=18&&a<=59;if(key==='60p')return a>=60;if(key==='65p')return a>=65;return true}
function sets(){const o={famAny:new Set,famOff:new Set,famLocal:new Set,personAny:new Set,personOff:new Set,personLocal:new Set};for(const v of state.visits||[]){if(!v.completed)continue;const fid=v.family_id?String(v.family_id):'',pid=v.person_id?String(v.person_id):'';if(fid)o.famAny.add(fid);if(pid)o.personAny.add(pid);if(v.official){if(fid)o.famOff.add(fid);if(pid)o.personOff.add(pid)}else{if(fid)o.famLocal.add(fid);if(pid)o.personLocal.add(pid)}}return o}
function visitMatch(id,prefix,s){if(state.visit==='all')return true;const any=s[prefix+'Any'],off=s[prefix+'Off'],loc=s[prefix+'Local'];if(state.visit==='visited')return any.has(id);if(state.visit==='not_visited')return!any.has(id);if(state.visit==='official')return off.has(id);if(state.visit==='local_only')return loc.has(id)&&!off.has(id);return true}
function recadStarted(f){return !!(f.recadastro_status||f.data_recadastramento||f.recadastro_visited_at)}
function distanceMatch(f){const m=f.geo_walk_distance_esf_m;if(state.distance==='all')return true;if(state.distance==='near')return m!=null&&Number(m)<=500;if(state.distance==='mid')return m!=null&&Number(m)>500&&Number(m)<=1000;if(state.distance==='far')return m!=null&&Number(m)>1000;if(state.distance==='none')return m==null;return true}
function qualityFamily(f,members){if(state.quality==='all')return true;if(state.quality==='no_phone')return!String(f.contact_phone||'').trim();if(state.quality==='no_birth')return members.some(p=>!p.birth_date);if(state.quality==='no_geo')return f.geo_walk_distance_esf_m==null;if(state.quality==='not_recad')return f.recadastro_concluido!==true;if(state.quality==='no_address')return!String(f.street||'').trim()||!String(f.number||'').trim();return true}
function qualityPerson(p,f){if(state.quality==='all')return true;if(state.quality==='no_phone')return!String(p.phone||f.contact_phone||'').trim();if(state.quality==='no_birth')return!p.birth_date;if(state.quality==='no_geo')return f.geo_walk_distance_esf_m==null;if(state.quality==='not_recad')return f.recadastro_concluido!==true;if(state.quality==='no_address')return!String(f.street||'').trim()||!String(f.number||'').trim();return true}
function familyCommon(f,search,s,opts={}){if(state.q&&!search.includes(N(state.q)))return false;if(state.street!=='all'&&String(f.street||'')!==state.street)return false;if(state.risk!=='all'&&String(f.family_risk||'')!==state.risk)return false;const isPbf=beneficiary(f),ps=pbfSummary(f);if((opts.forcePbf||state.pbf==='yes')&&!isPbf)return false;if(state.pbf==='no'&&isPbf)return false;if(state.pbf==='pending'&&(!isPbf||!(ps.pending>0||ps.notVerified>0)))return false;if(state.recad==='done'&&f.recadastro_concluido!==true)return false;if(state.recad==='pending'&&(f.recadastro_concluido===true||!recadStarted(f)))return false;if(state.recad==='not_started'&&recadStarted(f))return false;if(!opts.skipPhone){if(state.phone==='with'&&!String(f.contact_phone||'').trim())return false;if(state.phone==='without'&&String(f.contact_phone||'').trim())return false}if(state.geo==='confirmed'&&f.geo_verified!==true)return false;if(state.geo==='estimated'&&(f.geo_verified===true||f.geo_walk_distance_esf_m==null))return false;if(state.geo==='none'&&f.geo_walk_distance_esf_m!=null)return false;if(!distanceMatch(f))return false;if(!visitMatch(String(f.family_id),'fam',s))return false;return true}
function rows(){if(!state.snapshot)return[];const fams=state.snapshot.families||[],people=state.snapshot.people||[],fm=famMap(),mm=membersMap(),s=sets();if(['families','pbf','recad'].includes(state.mode)){return sort(fams.filter(f=>{const members=mm.get(String(f.family_id))||[],search=N([f.family_code,f.responsible_name,f.contact_phone,f.street,f.number,f.neighborhood,...members.map(p=>p.full_name)].join(' '));if(!familyCommon(f,search,s,{forcePbf:state.mode==='pbf'}))return false;if(state.condition!=='all'&&!members.some(p=>condMatch(p,state.condition)))return false;if(state.age!=='all'&&!members.some(p=>ageMatch(p,state.age)))return false;if(state.sex!=='all'&&!members.some(p=>String(p.sex||'')===state.sex))return false;if(state.role!=='all'&&!members.some(p=>String(p.role||'')===state.role))return false;if(!qualityFamily(f,members))return false;return true}))}
 if(state.mode==='people'){return sort(people.filter(p=>{const f=fm.get(String(p.family_id));if(!f)return false;const search=N([p.full_name,p.phone,p.relationship,p.role,f.family_code,f.responsible_name,f.street,f.number,f.neighborhood].join(' '));if(!familyCommon(f,search,s,{skipPhone:true}))return false;if(!condMatch(p,state.condition)||!ageMatch(p,state.age))return false;if(state.sex!=='all'&&String(p.sex||'')!==state.sex)return false;if(state.role!=='all'&&String(p.role||'')!==state.role)return false;if(!visitMatch(String(p.person_id),'person',s))return false;if(state.phone==='with'&&!String(p.phone||f.contact_phone||'').trim())return false;if(state.phone==='without'&&String(p.phone||f.contact_phone||'').trim())return false;if(!qualityPerson(p,f))return false;return true}))}
 if(state.mode==='visits'){return sort((state.visits||[]).filter(v=>{const f=fm.get(String(v.family_id));const search=N([v.full_name,v.family_code,v.responsible_name,v.street,v.number,v.neighborhood,v.source,v.status].join(' '));if(state.q&&!search.includes(N(state.q)))return false;if(state.street!=='all'&&String(v.street||'')!==state.street)return false;if(state.source==='official'&&!v.official)return false;if(state.source==='local'&&v.official)return false;if(state.pbf==='yes'&&(!f||!beneficiary(f)))return false;if(state.pbf==='no'&&f&&beneficiary(f))return false;if(state.role!=='all'&&v.person_id){const p=people.find(x=>String(x.person_id)===String(v.person_id));if(!p||String(p.role||'')!==state.role)return false}return true}))}
 if(state.mode==='tasks'){return sort((state.snapshot.tasks||[]).filter(t=>{const search=N([t.full_name,t.title,t.task_type,t.family_code,t.responsible_name,t.street,t.number,t.neighborhood].join(' '));if(state.q&&!search.includes(N(state.q)))return false;if(state.street!=='all'&&String(t.street||'')!==state.street)return false;if(state.priority!=='all'&&String(t.priority||'')!==state.priority)return false;return true}))}return[]}
function sort(list){const fm=famMap();return list.slice().sort((a,b)=>{const fa=a.family_id?fm.get(String(a.family_id)):a,fb=b.family_id?fm.get(String(b.family_id)):b;if(state.sort==='name')return String(a.full_name||a.responsible_name||'').localeCompare(String(b.full_name||b.responsible_name||''),'pt-BR');if(state.sort==='number')return houseNo(a.number||fa?.number)-houseNo(b.number||fb?.number);if(state.sort==='last_visit')return String(a.last_official_visit||fa?.last_official_visit||'0000').localeCompare(String(b.last_official_visit||fb?.last_official_visit||'0000'));if(state.sort==='age')return Number(b.age??-1)-Number(a.age??-1);if(state.sort==='date')return String(b.visit_date||b.due_date||'').localeCompare(String(a.visit_date||a.due_date||''));return String(a.street||fa?.street||'ZZZ').localeCompare(String(b.street||fb?.street||'ZZZ'),'pt-BR')||houseNo(a.number||fa?.number)-houseNo(b.number||fb?.number)||String(a.full_name||a.responsible_name||'').localeCompare(String(b.full_name||b.responsible_name||''),'pt-BR')})}
function kpis(list){const s=sets();if(state.mode==='visits'){const done=list.filter(x=>x.completed);return[[list.length,'Registros'],[done.length,'Realizadas'],[done.filter(x=>x.official).length,'Oficiais'],[done.filter(x=>!x.official).length,'Locais']]}if(state.mode==='people')return[[list.length,'Pessoas'],[list.filter(p=>s.personAny.has(String(p.person_id))).length,'Visitadas'],[list.filter(p=>String(p.phone||'').trim()).length,'Telefone próprio'],[list.filter(p=>p.age!=null&&p.age>=60).length,'60+']];if(state.mode==='pbf')return[[list.length,'Famílias PBF'],[list.filter(f=>pbfSummary(f).reviewed>0).length,'Iniciadas'],[list.filter(f=>pbfSummary(f).pending>0||pbfSummary(f).notVerified>0).length,'A revisar'],[list.filter(f=>pbfSummary(f).pending>0).length,'Com pendência']];if(state.mode==='recad')return[[list.length,'Famílias'],[list.filter(f=>f.recadastro_concluido===true).length,'Concluídas'],[list.filter(f=>recadStarted(f)&&f.recadastro_concluido!==true).length,'Em andamento'],[list.filter(f=>!recadStarted(f)).length,'Não iniciadas']];if(state.mode==='tasks')return[[list.length,'Pendências'],[list.filter(t=>t.priority==='alta').length,'Alta prioridade'],[list.filter(t=>t.due_date&&t.due_date<today()).length,'Atrasadas'],[new Set(list.map(t=>t.family_id).filter(Boolean)).size,'Famílias']];return[[list.length,'Famílias'],[list.filter(f=>s.famAny.has(String(f.family_id))).length,'Visitadas'],[list.filter(f=>!s.famAny.has(String(f.family_id))).length,'Sem visita'],[list.filter(beneficiary).length,'Bolsa Família']]}
function streetOptions(){return(state.snapshot?.streets||[]).map(x=>x.street).filter(Boolean)}
function riskOptions(){return[...new Set((state.snapshot?.families||[]).map(f=>String(f.family_risk||'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function sexOptions(){return[...new Set((state.snapshot?.people||[]).map(p=>String(p.sex||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function pills(){const out=[],[a,b]=period();if(['families','people','visits'].includes(state.mode))out.push(`Período: ${F(a)}–${F(b)}`);if(state.street!=='all')out.push('Rua: '+T(state.street));if(state.visit!=='all')out.push('Visita: '+VISITS.find(x=>x[0]===state.visit)?.[1]);if(state.condition!=='all')out.push('Condição: '+CONDITIONS.find(x=>x[0]===state.condition)?.[1]);if(state.age!=='all')out.push('Idade: '+(state.age==='custom'?`${state.ageMin||'0'}–${state.ageMax||'∞'}`:AGES.find(x=>x[0]===state.age)?.[1]));if(state.sex!=='all')out.push('Sexo: '+state.sex);if(state.role!=='all')out.push('Papel: '+(state.role==='responsavel'?'Arrimo':'Integrante'));if(state.pbf!=='all')out.push('Bolsa Família: '+({yes:'beneficiárias',no:'não beneficiárias',pending:'a revisar'}[state.pbf]||state.pbf));if(state.recad!=='all')out.push('Recadastro: '+({done:'concluído',pending:'em andamento',not_started:'não iniciado'}[state.recad]||state.recad));if(state.phone!=='all')out.push('Telefone: '+(state.phone==='with'?'com':'sem'));if(state.geo!=='all')out.push('Geo: '+({confirmed:'GPS',estimated:'estimada',none:'sem geo'}[state.geo]||state.geo));if(state.distance!=='all')out.push('Distância: '+({near:'≤500 m',mid:'500 m–1 km',far:'>1 km',none:'sem rota'}[state.distance]||state.distance));if(state.quality!=='all')out.push('Qualidade: '+({no_phone:'sem telefone',no_birth:'sem nascimento',no_geo:'sem geo',not_recad:'recadastro pendente',no_address:'endereço incompleto'}[state.quality]||state.quality));if(state.q)out.push('Busca: '+state.q);return out.filter(Boolean)}
function preset(id){state.preset=id;state.mode=PRESETS.find(x=>x[0]===id)?.[2]||'families';for(const k of ['visit','condition','age','sex','role','risk','pbf','recad','phone','geo','distance','source','priority','quality'])state[k]='all';state.ageMin='';state.ageMax='';state.sort=state.mode==='visits'||state.mode==='tasks'?'date':'street';if(id==='pbf')state.pbf='yes';remember();draw()}
function filters(){const customDate=state.period==='custom',customAge=state.age==='custom',task=state.mode==='tasks',visits=state.mode==='visits',sexes=sexOptions(),[a,b]=period();return `<div class="r3-card r3-filters"><h2>Filtros do relatório</h2><div class="r3-grid">
<div class="r3-field r3-search"><label>Buscar</label><input id="r3-q" value="${E(state.q)}" placeholder="Nome, família, rua, número, telefone…"></div>
<div class="r3-field"><label>Rua</label><select id="r3-street"><option value="all">Todas as ruas</option>${streetOptions().map(s=>`<option value="${E(s)}" ${state.street===s?'selected':''}>${E(T(s))}</option>`).join('')}</select></div>
<div class="r3-field"><label>Ordenar</label><select id="r3-sort"><option value="street" ${state.sort==='street'?'selected':''}>Rua e número</option><option value="name" ${state.sort==='name'?'selected':''}>Nome A–Z</option><option value="number" ${state.sort==='number'?'selected':''}>Número do imóvel</option><option value="last_visit" ${state.sort==='last_visit'?'selected':''}>Mais tempo sem visita</option><option value="age" ${state.sort==='age'?'selected':''}>Maior idade</option><option value="date" ${state.sort==='date'?'selected':''}>Data mais recente</option></select></div>
${!task?`<div class="r3-field"><label>Período</label><select id="r3-period"><option value="month" ${state.period==='month'?'selected':''}>Mês atual</option><option value="today" ${state.period==='today'?'selected':''}>Hoje</option><option value="7" ${state.period==='7'?'selected':''}>Últimos 7 dias</option><option value="30" ${state.period==='30'?'selected':''}>Últimos 30 dias</option><option value="3m" ${state.period==='3m'?'selected':''}>Últimos 3 meses</option><option value="6m" ${state.period==='6m'?'selected':''}>Últimos 6 meses</option><option value="12m" ${state.period==='12m'?'selected':''}>Últimos 12 meses</option><option value="custom" ${state.period==='custom'?'selected':''}>Período personalizado</option></select></div><div class="r3-field ${customDate?'':'r3-hidden'}" data-r3-custom-date><label>De</label><input id="r3-start" type="date" value="${E(customDate?state.start:a)}"></div><div class="r3-field ${customDate?'':'r3-hidden'}" data-r3-custom-date><label>Até</label><input id="r3-end" type="date" value="${E(customDate?state.end:b)}"></div>`:''}
${!task&&!visits?`<div class="r3-field"><label>Situação da visita</label><select id="r3-visit">${VISITS.map(([v,l])=>`<option value="${v}" ${state.visit===v?'selected':''}>${E(l)}</option>`).join('')}</select></div>`:''}
${visits?`<div class="r3-field"><label>Fonte da visita</label><select id="r3-source"><option value="all" ${state.source==='all'?'selected':''}>Todas</option><option value="official" ${state.source==='official'?'selected':''}>Oficial</option><option value="local" ${state.source==='local'?'selected':''}>Registro local</option></select></div>`:''}
${!task&&!visits?`<div class="r3-field"><label>Condição de saúde</label><select id="r3-condition">${CONDITIONS.map(([v,l])=>`<option value="${v}" ${state.condition===v?'selected':''}>${E(l)}</option>`).join('')}</select></div><div class="r3-field"><label>Faixa etária</label><select id="r3-age">${AGES.map(([v,l])=>`<option value="${v}" ${state.age===v?'selected':''}>${E(l)}</option>`).join('')}</select></div><div class="r3-field ${customAge?'':'r3-hidden'}" data-r3-custom-age><label>Idade mínima</label><input id="r3-age-min" type="number" min="0" max="120" value="${E(state.ageMin)}"></div><div class="r3-field ${customAge?'':'r3-hidden'}" data-r3-custom-age><label>Idade máxima</label><input id="r3-age-max" type="number" min="0" max="120" value="${E(state.ageMax)}"></div>${sexes.length?`<div class="r3-field"><label>Sexo cadastrado</label><select id="r3-sex"><option value="all">Todos / não informado</option>${sexes.map(s=>`<option value="${E(s)}" ${state.sex===s?'selected':''}>${E(T(s))}</option>`).join('')}</select></div>`:''}<div class="r3-field"><label>Papel na família</label><select id="r3-role"><option value="all" ${state.role==='all'?'selected':''}>Todos</option><option value="responsavel" ${state.role==='responsavel'?'selected':''}>Arrimo / responsável</option><option value="membro" ${state.role==='membro'?'selected':''}>Integrantes</option></select></div>`:''}
${!task?`<div class="r3-field"><label>Bolsa Família</label><select id="r3-pbf"><option value="all" ${state.pbf==='all'?'selected':''}>Todos</option><option value="yes" ${state.pbf==='yes'?'selected':''}>Beneficiárias</option><option value="pending" ${state.pbf==='pending'?'selected':''}>Com item pendente/não verificado</option><option value="no" ${state.pbf==='no'?'selected':''}>Não beneficiárias</option></select></div>`:''}
${!task&&!visits?`<div class="r3-field"><label>Recadastro</label><select id="r3-recad"><option value="all" ${state.recad==='all'?'selected':''}>Todos</option><option value="done" ${state.recad==='done'?'selected':''}>Concluído</option><option value="pending" ${state.recad==='pending'?'selected':''}>Em andamento</option><option value="not_started" ${state.recad==='not_started'?'selected':''}>Não iniciado</option></select></div><div class="r3-field"><label>Telefone</label><select id="r3-phone"><option value="all" ${state.phone==='all'?'selected':''}>Todos</option><option value="with" ${state.phone==='with'?'selected':''}>Com telefone</option><option value="without" ${state.phone==='without'?'selected':''}>Sem telefone</option></select></div><div class="r3-field"><label>Geolocalização</label><select id="r3-geo"><option value="all" ${state.geo==='all'?'selected':''}>Todas</option><option value="confirmed" ${state.geo==='confirmed'?'selected':''}>GPS confirmado</option><option value="estimated" ${state.geo==='estimated'?'selected':''}>Estimativa</option><option value="none" ${state.geo==='none'?'selected':''}>Sem geolocalização</option></select></div><div class="r3-field"><label>Distância a pé</label><select id="r3-distance"><option value="all" ${state.distance==='all'?'selected':''}>Todas</option><option value="near" ${state.distance==='near'?'selected':''}>Até 500 m</option><option value="mid" ${state.distance==='mid'?'selected':''}>500 m a 1 km</option><option value="far" ${state.distance==='far'?'selected':''}>Acima de 1 km</option><option value="none" ${state.distance==='none'?'selected':''}>Sem rota calculada</option></select></div><div class="r3-field"><label>Risco familiar</label><select id="r3-risk"><option value="all">Todos</option>${riskOptions().map(r=>`<option value="${E(r)}" ${state.risk===r?'selected':''}>${E(r)}</option>`).join('')}</select></div><div class="r3-field"><label>Qualidade cadastral</label><select id="r3-quality"><option value="all" ${state.quality==='all'?'selected':''}>Sem filtro</option><option value="no_phone" ${state.quality==='no_phone'?'selected':''}>Sem telefone</option><option value="no_birth" ${state.quality==='no_birth'?'selected':''}>Nascimento faltando</option><option value="no_geo" ${state.quality==='no_geo'?'selected':''}>Sem geolocalização</option><option value="not_recad" ${state.quality==='not_recad'?'selected':''}>Recadastro não concluído</option><option value="no_address" ${state.quality==='no_address'?'selected':''}>Endereço incompleto</option></select></div>`:''}
${task?`<div class="r3-field"><label>Prioridade</label><select id="r3-priority"><option value="all" ${state.priority==='all'?'selected':''}>Todas</option><option value="alta" ${state.priority==='alta'?'selected':''}>Alta</option><option value="media" ${state.priority==='media'?'selected':''}>Média</option><option value="baixa" ${state.priority==='baixa'?'selected':''}>Baixa</option></select></div>`:''}
<div class="r3-field"><label>Agrupar por</label><select id="r3-group"><option value="none" ${state.group==='none'?'selected':''}>Sem agrupamento</option><option value="street" ${state.group==='street'?'selected':''}>Rua</option>${!task&&!visits?`<option value="visit" ${state.group==='visit'?'selected':''}>Situação de visita</option><option value="risk" ${state.group==='risk'?'selected':''}>Risco</option><option value="pbf" ${state.group==='pbf'?'selected':''}>Bolsa Família</option><option value="recad" ${state.group==='recad'?'selected':''}>Recadastro</option>`:''}</select></div>
</div><div class="r3-actions"><button class="r3-btn primary" id="r3-apply">Aplicar filtros</button><button class="r3-btn gray" id="r3-clear">Limpar filtros</button></div><div class="r3-pills">${pills().map(x=>`<span class="r3-pill">${E(x)}</span>`).join('')}</div><div class="r3-note">Os filtros são combináveis. O resultado só é recalculado ao tocar em “Aplicar filtros”, evitando mudanças acidentais enquanto você monta o relatório.</div></div>`}
function readForm(){const r=$('#reports-v3');if(!r)return;const v=id=>$('#'+id,r)?.value;state.q=v('r3-q')||'';state.street=v('r3-street')||'all';state.sort=v('r3-sort')||'street';state.period=v('r3-period')||state.period;state.start=v('r3-start')||state.start;state.end=v('r3-end')||state.end;state.visit=v('r3-visit')||'all';state.source=v('r3-source')||'all';state.condition=v('r3-condition')||'all';state.age=v('r3-age')||'all';state.ageMin=v('r3-age-min')??state.ageMin;state.ageMax=v('r3-age-max')??state.ageMax;state.sex=v('r3-sex')||'all';state.role=v('r3-role')||'all';state.pbf=v('r3-pbf')||'all';state.recad=v('r3-recad')||'all';state.phone=v('r3-phone')||'all';state.geo=v('r3-geo')||'all';state.distance=v('r3-distance')||'all';state.risk=v('r3-risk')||'all';state.quality=v('r3-quality')||'all';state.priority=v('r3-priority')||'all';state.group=v('r3-group')||'none';if(state.period==='custom'&&state.start&&state.end&&state.start>state.end){toast('A data inicial não pode ser posterior à final.');return}remember();state.limit=100;ensureVisits().then(draw).catch(e=>{state.error=e.message;draw()})}
function clearFilters(){const keep={mode:state.mode,preset:state.preset};Object.assign(state,DEFAULT,keep);remember();ensureVisits(true).then(draw).catch(()=>draw())}
function groupKey(r){const f=r.family_id?famMap().get(String(r.family_id)):r,s=sets();if(state.group==='street')return T(r.street||f?.street||'Sem rua');if(state.group==='risk')return r.family_risk||f?.family_risk||'Sem risco';if(state.group==='pbf')return beneficiary(f)?'Bolsa Família':'Não Bolsa Família';if(state.group==='recad')return f?.recadastro_concluido?'Recadastro concluído':recadStarted(f)?'Recadastro em andamento':'Recadastro não iniciado';if(state.group==='visit'){const id=String(r.family_id||f?.family_id||'');return s.famOff.has(id)?'Com visita oficial':s.famLocal.has(id)?'Somente registro local':'Sem visita no período'}return''}
function grouped(list){if(state.group==='none')return[['',list]];const m=new Map;for(const r of list){const k=groupKey(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return[...m.entries()].sort((a,b)=>a[0].localeCompare(b[0],'pt-BR'))}
function visitBadge(f){const s=sets(),id=String(f.family_id);if(s.famOff.has(id))return['Oficial','ok'];if(s.famLocal.has(id))return['Local','warn'];return['Sem visita','bad']}
function heads(){if(state.mode==='people')return['Pessoa','Família','Endereço','Condições','Visita','Telefone'];if(state.mode==='visits')return['Data','Pessoa','Endereço','Fonte','Resultado'];if(state.mode==='pbf')return['Arrimo','Endereço','Telefone','Acompanhamento','Situação','Confirmação'];if(state.mode==='recad')return['Arrimo','Endereço','Situação','Data','Moradores','Cômodos','Risco'];if(state.mode==='tasks')return['Prazo','Pessoa/Família','Pendência','Prioridade','Endereço'];return['Família','Arrimo','Endereço','Membros','Visita','Risco','Bolsa Família','Recadastro','Geo']}
function familyTr(f){const vb=visitBadge(f),ps=pbfSummary(f);return `<tr><td>${E(f.family_code||'—')}</td><td><b>${E(T(f.responsible_name||''))}</b><br><small>${E(fmtPhone(f.contact_phone))}</small></td><td>${E(T([f.street,f.number].filter(Boolean).join(', ')))}</td><td>${f.member_count}</td><td><span class="r3-tag ${vb[1]}">${vb[0]}</span><br><small>${E(F(f.last_official_visit))}</small></td><td>${E(f.family_risk||'Sem risco')}</td><td>${beneficiary(f)?`<span class="r3-tag warn">PBF</span><br><small>${ps.reviewed}/${ps.expected} revisados</small>`:'—'}</td><td>${f.recadastro_concluido?'<span class="r3-tag ok">Concluído</span>':recadStarted(f)?'<span class="r3-tag warn">Em andamento</span>':'—'}</td><td>${E(fmtWalk(f.geo_walk_distance_esf_m))}${f.geo_verified?' · GPS':''}</td></tr>`}
function personTr(p){const f=famMap().get(String(p.family_id))||{},s=sets(),id=String(p.person_id),vb=s.personOff.has(id)?['Oficial','ok']:s.personLocal.has(id)?['Local','warn']:['Sem visita','bad'],flags=flagLabels(p);return `<tr><td><b>${E(T(p.full_name))}</b><br><small>${p.role==='responsavel'?'ARRIMO · ':''}${p.age==null?'idade —':p.age+' anos'}</small></td><td>${E(f.family_code||'—')}<br><small>${E(T(f.responsible_name||''))}</small></td><td>${E(T([f.street,f.number].filter(Boolean).join(', ')))}</td><td>${flags.length?flags.map(x=>`<span class="r3-tag">${E(x)}</span>`).join(' '):'—'}</td><td><span class="r3-tag ${vb[1]}">${vb[0]}</span><br><small>${E(F(p.last_official_visit))}</small></td><td>${E(fmtPhone(p.phone||f.contact_phone))}</td></tr>`}
function visitTr(v){return `<tr><td>${E(F(v.visit_date))}${v.visit_time?`<br><small>${E(String(v.visit_time).slice(0,5))}</small>`:''}</td><td><b>${E(T(v.full_name||''))}</b><br><small>${E(v.family_code||'—')}</small></td><td>${E(T([v.street,v.number].filter(Boolean).join(', ')))}</td><td><span class="r3-tag ${v.official?'ok':'warn'}">${v.official?'Oficial':'Local'}</span><br><small>${E(v.source||'')}</small></td><td>${E(v.status||'—')}</td></tr>`}
function pbfTr(f){const p=pbfSummary(f),pct=p.expected?Math.round(p.reviewed*100/p.expected):0;return `<tr><td><b>${E(T(f.responsible_name||''))}</b><br><small>${E(f.family_code||'—')}</small></td><td>${E(T([f.street,f.number].filter(Boolean).join(', ')))}</td><td>${E(fmtPhone(f.contact_phone))}</td><td>${p.reviewed}/${p.expected}<div class="r3-progress"><span style="width:${pct}%"></span></div></td><td>${p.pending?`<span class="r3-tag bad">${p.pending} pendente(s)</span>`:p.notVerified?`<span class="r3-tag warn">${p.notVerified} não verificado(s)</span>`:'<span class="r3-tag ok">Revisado</span>'}</td><td>${E(F(p.last))}</td></tr>`}
function recadTr(f){return `<tr><td><b>${E(T(f.responsible_name||''))}</b><br><small>${E(f.family_code||'—')}</small></td><td>${E(T([f.street,f.number].filter(Boolean).join(', ')))}</td><td>${f.recadastro_concluido?'<span class="r3-tag ok">Concluído</span>':recadStarted(f)?`<span class="r3-tag warn">${E(String(f.recadastro_status||'em andamento').replaceAll('_',' '))}</span>`:'<span class="r3-tag">Não iniciado</span>'}</td><td>${E(F(f.data_recadastramento||f.recadastro_visited_at))}</td><td>${f.moradores??'—'}</td><td>${f.comodos??'—'}</td><td>${E(f.recadastro_risco||f.family_risk||'—')}${f.risco_score!=null?` · ${f.risco_score}`:''}</td></tr>`}
function taskTr(t){const late=t.due_date&&t.due_date<today();return `<tr><td>${E(F(t.due_date))}${late?'<br><span class="r3-tag bad">Atrasada</span>':''}</td><td><b>${E(T(t.full_name||t.responsible_name||''))}</b><br><small>${E(t.family_code||'—')}</small></td><td>${E(t.title||t.task_type||'—')}</td><td><span class="r3-tag ${t.priority==='alta'?'bad':t.priority==='media'?'warn':''}">${E(t.priority||'—')}</span></td><td>${E(T([t.street,t.number].filter(Boolean).join(', ')))}</td></tr>`}
function tr(r){if(state.mode==='people')return personTr(r);if(state.mode==='visits')return visitTr(r);if(state.mode==='pbf')return pbfTr(r);if(state.mode==='recad')return recadTr(r);if(state.mode==='tasks')return taskTr(r);return familyTr(r)}
function mobile(r){const f=r.family_id?famMap().get(String(r.family_id)):r;if(state.mode==='visits')return `<div class="r3-mcard"><h3>${E(T(r.full_name||''))}</h3><div class="meta">${E(F(r.visit_date))} · ${r.official?'Oficial':'Local'}<br>${E(T([r.street,r.number].filter(Boolean).join(', ')))}</div><div class="r3-tags"><span class="r3-tag ${r.official?'ok':'warn'}">${E(r.status||'Visita')}</span></div></div>`;if(state.mode==='tasks')return `<div class="r3-mcard"><h3>${E(T(r.full_name||r.responsible_name||''))}</h3><div class="meta">${E(r.title||r.task_type||'Pendência')}<br>${E(T([r.street,r.number].filter(Boolean).join(', ')))} · ${E(F(r.due_date))}</div><div class="r3-tags"><span class="r3-tag ${r.priority==='alta'?'bad':'warn'}">${E(r.priority||'—')}</span></div></div>`;if(state.mode==='people'){const flags=flagLabels(r);return `<div class="r3-mcard"><h3>${E(T(r.full_name))}</h3><div class="meta">${r.age==null?'Idade não informada':r.age+' anos'} · Família ${E(f?.family_code||'—')}<br>${E(T([f?.street,f?.number].filter(Boolean).join(', ')))} · ${E(fmtPhone(r.phone||f?.contact_phone))}</div><div class="r3-tags">${flags.map(x=>`<span class="r3-tag">${E(x)}</span>`).join('')}</div></div>`}if(state.mode==='pbf'){const p=pbfSummary(r);return `<div class="r3-mcard"><h3>${E(T(r.responsible_name||''))}</h3><div class="meta">${E(T([r.street,r.number].filter(Boolean).join(', ')))}<br>${E(fmtPhone(r.contact_phone))}</div><div class="r3-tags"><span class="r3-tag warn">PBF</span><span class="r3-tag ${p.pending?'bad':p.notVerified?'warn':'ok'}">${p.reviewed}/${p.expected} revisados</span></div></div>`}if(state.mode==='recad')return `<div class="r3-mcard"><h3>${E(T(r.responsible_name||''))}</h3><div class="meta">${E(T([r.street,r.number].filter(Boolean).join(', ')))}<br>${E(F(r.data_recadastramento||r.recadastro_visited_at))}</div><div class="r3-tags"><span class="r3-tag ${r.recadastro_concluido?'ok':recadStarted(r)?'warn':''}">${r.recadastro_concluido?'Concluído':recadStarted(r)?'Em andamento':'Não iniciado'}</span></div></div>`;const vb=visitBadge(r);return `<div class="r3-mcard"><h3>${E(T(r.responsible_name||''))}</h3><div class="meta">Família ${E(r.family_code||'—')} · ${r.member_count} integrante(s)<br>${E(T([r.street,r.number].filter(Boolean).join(', ')))} · ${E(fmtPhone(r.contact_phone))}</div><div class="r3-tags"><span class="r3-tag ${vb[1]}">${vb[0]}</span>${beneficiary(r)?'<span class="r3-tag warn">Bolsa Família</span>':''}${r.recadastro_concluido?'<span class="r3-tag ok">Recad. concluído</span>':''}</div></div>`}
function results(list){const lim=state.limit==='all'?list.length:Number(state.limit||100),shown=list.slice(0,lim),groups=grouped(shown),h=heads();const tbody=groups.map(([g,rs])=>(g?`<tr><td colspan="${h.length}" class="r3-group">${E(g)} · ${rs.length}</td></tr>`:'')+rs.map(tr).join('')).join(''),cards=groups.map(([g,rs])=>(g?`<div class="r3-group" style="padding:7px 8px;margin:8px 0">${E(g)} · ${rs.length}</div>`:'')+rs.map(mobile).join('')).join('');return `<div class="r3-card"><div class="r3-resultsHead"><div><h2>${E(MODES[state.mode][0]+' '+MODES[state.mode][1])}</h2><div class="sub">${list.length} resultado(s) após os filtros. As exportações usam o conjunto completo filtrado.</div></div><div class="r3-actions"><button class="r3-btn teal" id="r3-csv">CSV</button><button class="r3-btn soft" id="r3-copy">Copiar resumo</button><button class="r3-btn gray" id="r3-print">Imprimir / PDF</button></div></div>${list.length?`<div class="r3-tableWrap"><table class="r3-table"><thead><tr>${h.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${tbody}</tbody></table></div><div class="r3-mobile">${cards}</div>${shown.length<list.length?`<div class="r3-actions"><button class="r3-btn soft" id="r3-more">Mostrar mais (${list.length-shown.length} restantes)</button></div>`:''}<div class="r3-note">Mostrando ${shown.length} de ${list.length}. O CSV inclui todos os resultados filtrados.</div>`:'<div class="r3-empty">Nenhum registro encontrado com os filtros selecionados.</div>'}</div>`}
function bars(list){if(!list.length||state.mode==='visits')return'';const m=new Map;for(const r of list){const f=r.family_id?famMap().get(String(r.family_id)):r,k=T(r.street||f?.street||'Sem rua');m.set(k,(m.get(k)||0)+1)}const top=[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6),max=top[0]?.[1]||1;return `<div class="r3-card r3-barsCard"><h2>Distribuição por rua</h2><div class="r3-bars">${top.map(([k,v])=>`<div class="r3-bar"><span>${E(k)}</span><div class="r3-track"><div class="r3-fill" style="width:${Math.round(v*100/max)}%"></div></div><b>${v}</b></div>`).join('')}</div></div>`}
function csvRows(list){let h=[],d=[];if(state.mode==='people'){h=['Pessoa','Idade','Papel','Família','Arrimo','Rua','Número','Condições','Última visita oficial','Telefone'];d=list.map(p=>{const f=famMap().get(String(p.family_id))||{};return[p.full_name,p.age??'',p.role||'',f.family_code,f.responsible_name,f.street,f.number,flagLabels(p).join(', '),p.last_official_visit||'',p.phone||f.contact_phone||'']})}else if(state.mode==='visits'){h=['Data','Hora','Pessoa','Família','Arrimo','Rua','Número','Fonte','Oficial','Resultado'];d=list.map(v=>[v.visit_date,v.visit_time||'',v.full_name,v.family_code,v.responsible_name,v.street,v.number,v.source,v.official?'Sim':'Não',v.status])}else if(state.mode==='pbf'){h=['Família','Arrimo','Rua','Número','Telefone','Itens revisados','Itens esperados','Em dia','Pendências','Não verificados','Última confirmação'];d=list.map(f=>{const p=pbfSummary(f);return[f.family_code,f.responsible_name,f.street,f.number,f.contact_phone,p.reviewed,p.expected,p.ok,p.pending,p.notVerified,p.last||'']})}else if(state.mode==='recad'){h=['Família','Arrimo','Rua','Número','Situação','Data','Moradores','Cômodos','Risco','Score'];d=list.map(f=>[f.family_code,f.responsible_name,f.street,f.number,f.recadastro_concluido?'Concluído':recadStarted(f)?f.recadastro_status||'Em andamento':'Não iniciado',f.data_recadastramento||'',f.moradores??'',f.comodos??'',f.recadastro_risco||f.family_risk||'',f.risco_score??''])}else if(state.mode==='tasks'){h=['Prazo','Pessoa','Família','Arrimo','Rua','Número','Pendência','Tipo','Prioridade'];d=list.map(t=>[t.due_date||'',t.full_name||'',t.family_code||'',t.responsible_name||'',t.street||'',t.number||'',t.title||'',t.task_type||'',t.priority||''])}else{h=['Família','Arrimo','Rua','Número','Telefone','Integrantes','Última visita oficial','Última visita operacional','Risco','Bolsa Família','Recadastro','Distância a pé (m)','GPS confirmado'];d=list.map(f=>[f.family_code,f.responsible_name,f.street,f.number,f.contact_phone,f.member_count,f.last_official_visit||'',f.last_operational_visit||'',f.family_risk,beneficiary(f)?'Sim':'Não',f.recadastro_concluido?'Concluído':recadStarted(f)?'Em andamento':'Não iniciado',f.geo_walk_distance_esf_m??'',f.geo_verified?'Sim':'Não'])}return[h,...d]}
function download(list){const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv='\ufeff'+csvRows(list).map(r=>r.map(q).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`esf06-relatorio-${state.mode}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function summary(list){const[a,b]=period(),ks=kpis(list),txt=[`ESF 06 — ${MODES[state.mode][1]}`,`Gerado em: ${new Date().toLocaleString('pt-BR')}`,`Período: ${F(a)} a ${F(b)}`,...ks.map(x=>`${x[1]}: ${x[0]}`),...pills().map(x=>'Filtro: '+x)].join('\n');navigator.clipboard?.writeText(txt).then(()=>toast('Resumo copiado.')).catch(()=>toast('Não foi possível copiar.'))}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;$('#toasts')?.appendChild(d);setTimeout(()=>d.remove(),3000)}
function bind(list){const r=$('#reports-v3');if(!r)return;$$('[data-r3-preset]',r).forEach(b=>b.onclick=()=>preset(b.dataset.r3Preset));$('#r3-refresh',r)?.addEventListener('click',()=>load(true));$('#r3-apply',r)?.addEventListener('click',readForm);$('#r3-clear',r)?.addEventListener('click',clearFilters);$('#r3-period',r)?.addEventListener('change',e=>$$('[data-r3-custom-date]',r).forEach(x=>x.classList.toggle('r3-hidden',e.target.value!=='custom')));$('#r3-age',r)?.addEventListener('change',e=>$$('[data-r3-custom-age]',r).forEach(x=>x.classList.toggle('r3-hidden',e.target.value!=='custom')));$('#r3-q',r)?.addEventListener('keydown',e=>{if(e.key==='Enter')readForm()});$('#r3-csv',r)?.addEventListener('click',()=>download(list));$('#r3-copy',r)?.addEventListener('click',()=>summary(list));$('#r3-print',r)?.addEventListener('click',()=>window.print());$('#r3-more',r)?.addEventListener('click',()=>{state.limit=Math.min(list.length,Number(state.limit||100)+100);draw()})}
function draw(){if(!reportActive())return;injectStyle();if(!state.snapshot){app.innerHTML=`<div id="reports-v3"><section class="r3-hero"><h1>📄 Central de Relatórios</h1><p>Carregando os dados operacionais do Supabase…</p></section>${state.error?`<div class="r3-error">${E(state.error)}</div>`:'<div class="r3-loading">Preparando relatórios, indicadores e filtros…</div>'}</div>`;if(!state.loading)load();return}const list=rows(),ks=kpis(list);app.innerHTML=`<div id="reports-v3"><section class="r3-hero"><div class="r3-heroTop"><div><h1>📄 Central de Relatórios</h1><p>Relatórios combináveis de cobertura, condições de saúde, Bolsa Família, recadastro, visitas e pendências.</p><div class="r3-updated">Dados atualizados ${state.generatedAt?new Date(state.generatedAt).toLocaleString('pt-BR'):'agora'} · ESF 06</div></div><button class="r3-refresh" id="r3-refresh">↻ Atualizar dados</button></div></section>${state.error?`<div class="r3-error">${E(state.error)}</div>`:''}<div class="r3-presets">${PRESETS.map(([id,label,mode])=>`<button class="r3-preset ${state.preset===id?'on':''}" data-r3-preset="${id}">${E(MODES[mode][0])} ${E(label)}</button>`).join('')}</div><div class="r3-kpis">${ks.map((x,i)=>`<div class="r3-kpi ${i===1?'ok':i===2?'bad':i===3?'warn':''}"><b>${x[0]}</b><span>${E(x[1])}</span></div>`).join('')}</div>${filters()}${bars(list)}${results(list)}</div>`;bind(list)}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;if(reportActive()&&!$('#reports-v3'))draw()})}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('load',schedule,{once:true});schedule();
})();
