(()=>{
'use strict';
const BASE='https://pvwqxpqetdxtmqqypqjk.supabase.co/functions/v1';
const OLD=BASE+'/acs-visita-api';
const SMART=BASE+'/acs-route-tools';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleCase=v=>String(v||'').toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase());
const key=()=>new URL(location.href).searchParams.get('k')||localStorage.getItem('esf06_visit_key')||'';
const routeDate=()=>document.getElementById('route-date')?.value||new Date().toISOString().slice(0,10);
const plusDays=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const fmt=v=>{if(!v)return'—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v};
async function call(url,api,opts={}){const u=new URL(url);u.searchParams.set('api',api);u.searchParams.set('k',key());Object.entries(opts.params||{}).forEach(([a,b])=>u.searchParams.set(a,String(b)));const r=await fetch(u,{method:opts.method||'GET',headers:opts.body?{'content-type':'application/json'}:undefined,body:opts.body?JSON.stringify(opts.body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Falha de comunicação'}));if(!r.ok)throw new Error(j.error||'Erro');return j}
function toast(msg,type='ok'){const stack=document.getElementById('toasts')||document.body;const d=document.createElement('div');d.className='toast '+type;d.textContent=msg;stack.appendChild(d);setTimeout(()=>d.remove(),3600)}
function refreshRoute(){const input=document.getElementById('route-date');if(input)input.dispatchEvent(new Event('change',{bubbles:true}));}
function riskText(x){const t=[];if(x.last_visit==null)t.push('Nunca visitado');else if(Number(x.days_since)>=30)t.push(`${x.days_since} dias sem visita`);if(Number(x.need_score)>=80)t.push('Necessidade muito alta');else if(Number(x.need_score)>=55)t.push('Necessidade alta');else if(Number(x.need_score)>=30)t.push('Necessidade moderada');return t;}
function suggestCard(x,i){const tags=[`<span class="smart-tag near">${esc(x.proximity_label||'Próximo')}</span>`,...riskText(x).map((t,j)=>`<span class="smart-tag ${j?'hot':''}">${esc(t)}</span>`)];if(x.number_distance!=null)tags.push(`<span class="smart-tag">≈ ${esc(x.number_distance)} nº de diferença</span>`);return `<div class="smart-suggest-card ${Number(x.proximity_tier)===0?'same-street':''}"><div class="smart-suggest-top"><div class="smart-suggest-rank">${i+1}</div><div style="flex:1"><div class="smart-suggest-name">${esc(titleCase(x.full_name))}</div><div class="smart-suggest-address">📍 ${esc([x.street,x.number,x.neighborhood].filter(Boolean).join(', ')||'Endereço incompleto')}</div><div class="smart-tags">${tags.join('')}</div></div></div><div class="smart-suggest-actions"><button class="btn teal" data-smart-add="${x.person_id}">Adicionar ao roteiro</button></div></div>`}
async function renderSuggestions(host){
 if(!host||host.dataset.smartLoaded==='1')return;
 host.dataset.smartLoaded='1';
 const wrap=document.createElement('div');wrap.className='smart-suggest-wrap';wrap.innerHTML='<div class="smart-suggest-head"><span class="ico">✨</span><div><strong>Sugestões próximas e prioritárias</strong><small>Calculando 5 visitas a partir do endereço já programado...</small></div></div>';
 host.appendChild(wrap);
 try{
  const r=await call(SMART,'suggestions',{params:{date:routeDate()}});
  if(!r.pivot){wrap.innerHTML='<div class="smart-empty">Programe pelo menos uma visita. Assim que houver um endereço-base, eu procuro automaticamente até 5 pessoas prioritárias próximas.</div>';return}
  const rows=r.rows||[];
  wrap.innerHTML=`<div class="smart-suggest-head"><span class="ico">✨</span><div><strong>${rows.length?`${rows.length} sugestões para aproveitar o trajeto`:'Nenhuma sugestão prioritária próxima'}</strong><small>Base: ${esc(titleCase(r.pivot.patient_name))} · ${esc([r.pivot.street,r.pivot.number].filter(Boolean).join(', '))}</small></div></div>${rows.length?rows.map(suggestCard).join(''):'<div class="smart-empty">Não encontrei pessoas com necessidade de visita na mesma rua ou bairro que não estejam já no roteiro.</div>'}<div class="smart-source">Prioridade calculada com histórico de visitas e marcadores do cadastro; proximidade calculada somente por rua, bairro e número.</div>`;
  wrap.querySelectorAll('[data-smart-add]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Adicionando...';try{const score=Number(rows.find(x=>x.person_id===b.dataset.smartAdd)?.need_score||0);await call(OLD,'save_agenda',{method:'POST',body:{person_id:b.dataset.smartAdd,scheduled_date:routeDate(),reason:'Sugestão automática: visita prioritária próxima ao trajeto',priority_block:score>=70?'prioridade':score>=40?'atencao':'rotina'}});toast('Visita adicionada ao roteiro.');refreshRoute()}catch(e){toast(e.message,'err');b.disabled=false;b.textContent='Adicionar ao roteiro'}});
 }catch(e){wrap.innerHTML=`<div class="smart-empty">Não consegui gerar as sugestões agora: ${esc(e.message)}</div>`}
}
function closeMenus(except){document.querySelectorAll('.route-menu').forEach(m=>{if(m!==except)m.remove()})}
function dateModal(itemId,name,current){const back=document.createElement('div');back.className='smart-date-modal';const def=plusDays(current,1);back.innerHTML=`<div class="smart-date-box"><h3>Reagendar visita</h3><p>${esc(titleCase(name))}</p><label>Nova data</label><input type="date" id="smart-new-date" value="${def}" min="${new Date().toISOString().slice(0,10)}"><div class="smart-date-actions"><button class="btn soft" data-cancel>Cancelar</button><button class="btn teal" data-save>Reagendar</button></div></div>`;document.body.appendChild(back);back.querySelector('[data-cancel]').onclick=()=>back.remove();back.onclick=e=>{if(e.target===back)back.remove()};back.querySelector('[data-save]').onclick=async e=>{const d=back.querySelector('#smart-new-date').value;if(!d)return toast('Escolha a nova data.','warn');e.currentTarget.disabled=true;try{await call(SMART,'reschedule',{method:'POST',body:{id:itemId,new_date:d}});back.remove();toast(`Visita reagendada para ${fmt(d)}.`);refreshRoute()}catch(err){toast(err.message,'err');e.currentTarget.disabled=false}}}
function enhanceMenus(list){list.querySelectorAll('.route-item').forEach(card=>{if(card.dataset.smartMenu==='1')return;const done=card.querySelector('[data-route-done]'),row=card.querySelector('.btn-row');if(!done||!row)return;card.dataset.smartMenu='1';const id=done.dataset.routeDone,name=card.querySelector('.route-name')?.textContent||'Visita';const wrap=document.createElement('div');wrap.className='route-menu-wrap';wrap.innerHTML='<button class="route-menu-btn" type="button" aria-label="Opções da visita">⋮</button>';row.appendChild(wrap);wrap.querySelector('button').onclick=e=>{e.stopPropagation();closeMenus();const menu=document.createElement('div');menu.className='route-menu';menu.innerHTML='<button data-postpone>⏭️ Adiar para amanhã</button><button data-reschedule>📅 Reagendar...</button>';wrap.appendChild(menu);menu.querySelector('[data-postpone]').onclick=async()=>{const d=plusDays(routeDate(),1);try{await call(SMART,'reschedule',{method:'POST',body:{id,new_date:d}});toast(`Visita adiada para ${fmt(d)}.`);refreshRoute()}catch(err){toast(err.message,'err')}};menu.querySelector('[data-reschedule]').onclick=()=>dateModal(id,name,routeDate())}})});
}
async function enhance(){const input=document.getElementById('route-date'),list=document.getElementById('route-list');if(!input||!list)return;enhanceMenus(list);const card=list.closest('.card');if(card&&!card.querySelector('.smart-suggest-wrap'))await renderSuggestions(card)}
const obs=new MutationObserver(()=>{setTimeout(enhance,40)});obs.observe(document.documentElement,{subtree:true,childList:true});
document.addEventListener('click',e=>{if(!e.target.closest('.route-menu-wrap'))closeMenus()});
setTimeout(enhance,500);
})();