(()=>{'use strict';
const fmtDate=()=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date()).replace(/^./,c=>c.toUpperCase());
function active(id){return !!document.querySelector(`[data-nav="${id}"].on`)}
function enhanceHeader(){const h=document.querySelector('.profile-inner');if(!h||h.querySelector('.v39-version'))return;const b=document.createElement('span');b.className='v39-version';b.textContent='PRODUÇÃO · V39';h.appendChild(b)}
function renameNav(){const p=document.querySelector('[data-nav="patients"]');if(p){const spans=p.querySelectorAll('span');if(spans[1]&&spans[1].textContent!=='Famílias')spans[1].textContent='Famílias'}}
function familyDashboard(){if(!active('patients'))return;const st=document.getElementById('stage');if(!st||st.querySelector('.v39-dashboard'))return;const api=window.ESF06PopulationFilters;if(!api)return;const fam=api.families?.()||[],rows=api.rows?.()||[];if(!fam.length||!rows.length)return;const visited=fam.filter(x=>x.v).length,due=fam.length-visited,known=rows.filter(p=>api.age?.(p)!=null).length;const d=document.createElement('section');d.className='v39-dashboard';d.innerHTML=`<div class="v39-dash-main"><small>Minha microárea</small><b>ESF 06 · visão de hoje</b><span class="v39-dash-date">${fmtDate()}</span></div><div class="v39-dash-stat"><small>Famílias</small><b>${fam.length}</b></div><div class="v39-dash-stat good"><small>Visitadas no mês</small><b>${visited}</b></div><div class="v39-dash-stat due"><small>Sem visita</small><b>${due}</b></div>`;const page=st.querySelector('.page');if(page)st.insertBefore(d,page);else st.prepend(d);const heroTitle=st.querySelector('.hero-title'),heroSub=st.querySelector('.hero-sub');if(heroTitle)heroTitle.innerHTML='<span class="hero-icon">🏠</span>Famílias da microárea';if(heroSub)heroSub.textContent=`${rows.length} pessoas ativas · ${known} com idade conhecida · cadastro e visitas em um só lugar.`}
function markBody(){document.body.classList.toggle('v39-patients',active('patients'));document.body.classList.toggle('v39-plan',active('plan'));document.body.classList.toggle('v39-more',active('more'))}
function run(){enhanceHeader();renameNav();markBody();familyDashboard()}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(run,45)}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('load',()=>{run();setTimeout(run,650);setTimeout(run,1600)});setInterval(()=>{if(active('patients')&&!document.querySelector('.v39-dashboard'))run()},1800);
})();
